import { useEffect, useState } from "react";
import { BookOpen, CheckCircle, LockSimple, MagnifyingGlass } from "@phosphor-icons/react";
import { languageTag, localized } from "../../i18n";
import { KeyboardInput, KeyboardTextarea, useKeyboard } from "../../mobile";
import { jsonBody, relationshipApi } from "../relationship/api";
import { ShareComposer } from "./ShareComposer";
import type { MemoryRecord, MemorySource, WorkspaceProps } from "./types";
import "./memory.css";

export function MemoryWorkspace({ language, userId, relationshipId = null, onChanged }: WorkspaceProps) {
  const [memories, setMemories] = useState<MemoryRecord[]>([]); const [sources, setSources] = useState<MemorySource[]>([]);
  const [text, setText] = useState(""); const [sourceId, setSourceId] = useState(""); const [allowPrivateAI, setAllowPrivateAI] = useState(false);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [sharing, setSharing] = useState(""); const [editing, setEditing] = useState(""); const [editText, setEditText] = useState(""); const [editAI, setEditAI] = useState(false); const [deleting, setDeleting] = useState("");
  const keyboard = useKeyboard();
  const t = (zh: string, en: string, es: string) => localized(language, zh, en, es);
  const load = async () => { const result = await relationshipApi<{ memories: MemoryRecord[] }>(`/api/memories?language=${language}`); setMemories(result.memories); };
  useEffect(() => { const reload = () => { void load().catch(() => {}); }; window.addEventListener("toward-us:assistant-changed", reload); return () => window.removeEventListener("toward-us:assistant-changed", reload); }, [language, userId, relationshipId]);
  useEffect(() => {
    let active = true; setLoading(true); setMemories([]); setSources([]); setSharing(""); setEditing(""); setNotice("");
    Promise.all([relationshipApi<{ memories: MemoryRecord[] }>(`/api/memories?language=${language}`), relationshipApi<{ sources: MemorySource[] }>(`/api/memories/sources?language=${language}`)]).then(([records, references]) => { if (active) { setMemories(records.memories); setSources(references.sources); } }).catch((error) => { if (active) setNotice(error.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [userId, relationshipId, language]);
  const changed = async () => { await load(); await onChanged?.(); };
  const run = async (action: () => Promise<unknown>, success = "") => { setBusy(true); setNotice(""); try { await action(); await changed(); setNotice(success); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const mutate = (record: MemoryRecord, action: string, body: Record<string, unknown> = {}) => run(() => relationshipApi(`/api/memories/${record.id}/${action}`, jsonBody({ expectedVersion: record.version, language, ...body })));
  const selectedSource = sources.find((source) => source.id === sourceId);
  const visible = memories.filter((record) => (filter === "all" || (filter === "private" ? record.visibility === "private" : record.visibility !== "private")) && record.text.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  const sourceLabel = (record: MemoryRecord) => record.provenance.source === "outcome_review" ? t("我选择的复盘", "A review I selected", "Una revisión que elegí") : record.provenance.source === "owner_confirmed_text" ? (record.provenance.sourceType === "outcome_review" ? t("本人确认分享的复盘经验", "Owner-confirmed review experience", "Experiencia de revisión compartida por su autor") : t("本人确认的分享", "Owner-confirmed share", "Texto compartido confirmado por su autor")) : t("我写下的话", "Words I chose to keep", "Palabras que elegí guardar");
  return <section className="relationship-feature memory-workspace" aria-labelledby="memory-title">
    <header><div><BookOpen size={24} /><h2 id="memory-title">{t("把有用的经验留下", "Keep what helps you", "Guarda lo que te ayuda")}</h2></div><p>{t("偏好可以改变，约定也会过时。你能纠正、归档或停止 AI 使用；共同经验需要双方确认。", "Preferences change and agreements can grow outdated. Correct, archive, or stop AI use. Shared experiences need both confirmations.", "Las preferencias cambian y los acuerdos pueden quedar obsoletos. Corrige, archiva o retira el uso de IA. Las experiencias compartidas requieren ambas confirmaciones.")}</p></header>
    <form className="memory-composer" onSubmit={(event) => { event.preventDefault(); void run(async () => {
      await relationshipApi("/api/memories", jsonBody({ text, allowPrivateAI, source: selectedSource || { type: "member" }, language })); setText(""); setSourceId(""); setAllowPrivateAI(false);
    }, t("已保存在你的私人空间。", "Saved in your private space.", "Guardado en tu espacio privado.")); }}>
      <label><span>{t("有什么值得下次记得？", "What would help to remember next time?", "¿Qué ayudaría recordar la próxima vez?")}</span><KeyboardTextarea onBlur={() => keyboard.hide()} value={text} onChange={(event) => setText(event.target.value)} maxLength={2000} placeholder={t("例如：下班后先安静半小时，我会更愿意聊天。", "For example: Half an hour of quiet after work helps me feel ready to talk.", "Por ejemplo: Media hora tranquila después del trabajo me ayuda a tener ganas de hablar.")} /></label>
      {sources.length > 0 && <details className="memory-source-picker"><summary>{t("从我已提交的复盘中挑选", "Choose from a review I submitted", "Elegir de una revisión que envié")}</summary><label><span>{t("选择来源，然后用自己的话确认经验", "Choose a source, then confirm the experience in your words", "Elige una fuente y confirma la experiencia con tus palabras")}</span><select value={sourceId} onChange={(event) => setSourceId(event.target.value)}><option value="">{t("不引用复盘", "No review reference", "Sin referencia a una revisión")}</option>{sources.map((source) => <option key={source.id} value={source.id}>{new Date(source.createdAt).toLocaleDateString(languageTag(language))} · {source.text.slice(0, 60)}</option>)}</select></label>{selectedSource && <blockquote>{selectedSource.text}</blockquote>}</details>}
      <label className="memory-checkbox"><input type="checkbox" checked={allowPrivateAI} onChange={(event) => setAllowPrivateAI(event.target.checked)} /><span>{t("允许我的私人 Agent 在以后对话中引用这条记忆", "Let my private Agent refer to this memory in future conversations", "Permitir que mi agente privado use este recuerdo en futuras conversaciones")}</span></label>
      <button disabled={busy || !text.trim()} type="submit"><LockSimple size={17} />{t("存为私人记忆", "Save privately", "Guardar en privado")}</button>
    </form>
    <div className="memory-toolbar"><label className="memory-search"><MagnifyingGlass size={18} /><KeyboardInput onBlur={() => keyboard.hide()} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("搜索记忆中的话", "Search your memories", "Buscar recuerdos")} aria-label={t("搜索记忆", "Search memories", "Buscar recuerdos")} /></label><label><span className="memory-sr-only">{t("筛选记忆", "Filter memories", "Filtrar recuerdos")}</span><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">{t("全部", "All", "Todos")}</option><option value="private">{t("只看私人", "Private", "Privados")}</option><option value="shared">{t("共同记录", "Shared", "Compartidos")}</option></select></label><button className="memory-quiet" disabled={busy} onClick={() => void run(async () => {})}>{t("刷新", "Refresh", "Actualizar")}</button></div>
    {loading ? <p role="status">{t("正在找回你的记录…", "Loading your memories…", "Cargando tus recuerdos…")}</p> : visible.length === 0 ? <p className="memory-empty">{query || filter !== "all" ? t("没有匹配的记忆，试试别的词。", "No matching memories. Try another word.", "No hay recuerdos que coincidan. Prueba otra palabra.") : t("还没有需要留下的经验。想到一句时，再写下来就好。", "Nothing to keep yet. When a useful thought comes, you can leave it here.", "Todavía no hay experiencias guardadas. Cuando llegue una idea útil, puedes dejarla aquí.")}</p> : <ol className="memory-timeline">{visible.map((record) => {
      const isPrivate = record.visibility === "private"; const own = record.ownerUserId === userId; const approved = record.approvals?.some((approval) => approval.userId === userId && approval.version === record.version); const expired = Boolean(record.expiresAt && Date.parse(record.expiresAt) <= Date.now());
      return <li key={record.id}><article className="memory-entry"><div className="memory-meta"><span>{isPrivate ? t("只有我可见", "Only me", "Solo yo") : t("双方可见", "Visible to both", "Visible para ambos")}</span><span>v{record.version}</span><time dateTime={record.updatedAt}>{new Date(record.updatedAt).toLocaleDateString(languageTag(language))}</time></div><p className="memory-text">{record.text}</p><p className="memory-provenance">{t("来源", "Source", "Fuente")} · {sourceLabel(record)}{record.provenance.sourceVersion ? ` · v${record.provenance.sourceVersion}` : ""}{record.provenance.correctedAt ? t(" · 已纠正", " · Corrected", " · Corregido") : ""}</p>
        <p className="memory-consent">{record.archivedAt ? t("已归档 · AI 不再引用", "Archived · AI will not use this", "Archivado · La IA ya no lo usará") : expired ? t("已过期 · AI 不再引用", "Expired · AI will not use this", "Caducado · La IA ya no lo usará") : record.withdrawnAt ? t("已撤回未来 AI 使用授权；已分享的文字仍可查看。", "Future AI use withdrawn; shared text remains visible.", "Uso futuro de IA retirado; el texto compartido sigue visible.") : record.aiAccessScope === "joint" ? t("双方已确认此版本 · 共同 AI 可引用", "Both confirmed this version · Joint AI may use it", "Ambos confirmaron esta versión · La IA compartida puede usarla") : record.aiAccessScope === "private" ? t("只允许我的私人 Agent 引用", "Only my private Agent may use it", "Solo mi agente privado puede usarlo") : isPrivate ? t("已保存 · AI 没有使用授权", "Saved · No AI permission", "Guardado · Sin permiso de IA") : t("等待双方分别确认 · 共同 AI 尚不可引用", "Waiting for both confirmations · Not yet available to joint AI", "Esperando ambas confirmaciones · Aún no disponible para la IA compartida")}</p>
        {record.expiresAt && <p className="memory-provenance">{t("有效至", "Valid until", "Válido hasta")} {new Date(record.expiresAt).toLocaleDateString(languageTag(language))}</p>}
        {!record.archivedAt && <div className="memory-actions">
          {!isPrivate && !record.withdrawnAt && !expired && <button disabled={busy || approved} onClick={() => void mutate(record, "approve", { allowJointAI: true })}><CheckCircle size={17} />{approved ? t("我已确认此版本", "I confirmed this version", "Ya confirmé esta versión") : t("确认此版本，允许共同 AI 使用", "Confirm version and allow joint AI", "Confirmar versión y autorizar IA compartida")}</button>}
          {isPrivate && own && relationshipId && <button className="memory-quiet" disabled={busy} onClick={() => { setSharing(sharing === record.id ? "" : record.id); setEditing(""); }}>{t("准备一段分享", "Prepare a share", "Preparar un texto para compartir")}</button>}
          <button className="memory-quiet" disabled={busy} onClick={() => { setEditing(record.id); setEditText(record.text); setEditAI(record.aiAccessScope === "private"); setSharing(""); }}>{t("纠正", "Correct", "Corregir")}</button>
          {!record.withdrawnAt && (record.aiAccessScope !== "none" || !isPrivate) && <button className="memory-quiet" disabled={busy} onClick={() => void mutate(record, "withdraw")}>{t("停止未来 AI 使用", "Stop future AI use", "Detener el uso futuro de IA")}</button>}
          {isPrivate && own && <button className="memory-quiet" disabled={busy} onClick={() => void mutate(record, "archive")}>{t("归档", "Archive", "Archivar")}</button>}
        </div>}
        {isPrivate && own && <div className="memory-delete">{deleting === record.id ? <><p>{t("永久删除这条私人原文？已经分享的副本仍可查看。", "Permanently delete this private original? Shared copies remain visible.", "¿Borrar permanentemente este original privado? Las copias compartidas seguirán visibles.")}</p><button disabled={busy} onClick={() => void run(async () => { await relationshipApi(`/api/memories/${record.id}`, { method: "DELETE", body: JSON.stringify({ expectedVersion: record.version, language }) }); setDeleting(""); })}>{t("确认删除原文", "Delete original", "Borrar original")}</button><button className="memory-quiet" onClick={() => setDeleting("")}>{t("取消", "Cancel", "Cancelar")}</button></> : <button className="memory-quiet" disabled={busy} onClick={() => setDeleting(record.id)}>{t("删除私人原文", "Delete private original", "Borrar original privado")}</button>}</div>}
        {editing === record.id && <div className="memory-edit"><label><span>{isPrivate ? t("纠正这条私人记忆", "Correct this private memory", "Corregir este recuerdo privado") : t("修改后双方旧确认都会失效，需要重新确认。", "Changes invalidate both confirmations. Both must confirm again.", "Los cambios invalidan ambas confirmaciones. Ambos deberán confirmar de nuevo.")}</span><KeyboardTextarea onBlur={() => keyboard.hide()} value={editText} onChange={(event) => setEditText(event.target.value)} maxLength={2000} /></label>{isPrivate && <label className="memory-checkbox"><input type="checkbox" checked={editAI} onChange={(event) => setEditAI(event.target.checked)} /><span>{t("允许我的私人 Agent 引用修改后的文字", "Allow my private Agent to use the revised text", "Permitir que mi agente privado use el texto corregido")}</span></label>}<div className="memory-actions"><button disabled={busy || !editText.trim()} onClick={() => void run(async () => { await relationshipApi(`/api/memories/${record.id}`, { method: "PATCH", body: JSON.stringify({ text: editText, expectedVersion: record.version, allowPrivateAI: editAI, language }) }); setEditing(""); })}>{t("保存新版本", "Save new version", "Guardar nueva versión")}</button><button className="memory-quiet" disabled={busy} onClick={() => setEditing("")}>{t("取消", "Cancel", "Cancelar")}</button></div></div>}
        {sharing === record.id && <ShareComposer key={`${record.id}:${record.version}`} record={record} collection="memories" language={language} onShared={changed} onClose={() => setSharing("")} />}
      </article></li>;
    })}</ol>}
    {notice && <p role="status" className="relationship-notice">{notice}</p>}
  </section>;
}
