import { Eye, Gift, Plus } from "@phosphor-icons/react";
import { useState } from "react";
import { localized, type Language } from "../../i18n";
import { jsonBody, relationshipApi } from "../relationship/api";
import type { GraphRecord } from "../relationship/types";

export function ListsPanel({ language, lists, items, onChanged }: { language: Language; lists: GraphRecord[]; items: GraphRecord[]; onChanged: () => Promise<void> }) {
  const [listTitle, setListTitle] = useState(""); const [itemTitle, setItemTitle] = useState(""); const [selected, setSelected] = useState(""); const [surprise, setSurprise] = useState(false); const [notice, setNotice] = useState("");
  const createList = async () => { try { const result = await relationshipApi<{ list: GraphRecord }>("/api/lists", jsonBody({ title: listTitle, type: "gifts" })); setSelected(result.list.id); setListTitle(""); await onChanged(); } catch (error) { setNotice((error as Error).message); } };
  const addItem = async () => { if (!selected || !itemTitle) return; try { await relationshipApi(`/api/lists/${selected}/items`, jsonBody({ title: itemTitle, visibility: surprise ? "private_surprise" : "shared" })); setItemTitle(""); setSurprise(false); await onChanged(); setNotice(""); } catch (error) { setNotice((error as Error).message); } };
  const reveal = async (id: string) => { try { await relationshipApi(`/api/list-items/${id}/reveal`, jsonBody({})); await onChanged(); } catch (error) { setNotice((error as Error).message); } };
  const active = selected || lists[0]?.id || "";
  return <section className="relationship-feature" aria-labelledby="lists-title"><header><div><Gift size={23} /><h2 id="lists-title">{localized(language, "共同愿望与惊喜", "Wishlists & private surprises", "Deseos y sorpresas privadas")}</h2></div><p>{localized(language, "共同愿望双方可见；私人惊喜不会通过数量、通知或接口向对方泄露。", "Shared wishes are visible to both. Private surprises do not leak through counts, notifications, or responses.", "Los deseos compartidos son visibles para ambos. Las sorpresas privadas no se filtran mediante contadores, avisos ni respuestas.")}</p></header>
    {!lists.length ? <div className="relationship-form inline-form"><label><span>{localized(language, "新清单", "New list", "Nueva lista")}</span><input value={listTitle} onChange={(event) => setListTitle(event.target.value)} placeholder={localized(language, "我们的愿望清单", "Our wishlist", "Nuestra lista de deseos")} /></label><button onClick={createList} disabled={!listTitle}><Plus size={18} />{localized(language, "创建", "Create", "Crear")}</button></div> : <><div className="relationship-form compact-grid"><label><span>{localized(language, "清单", "List", "Lista")}</span><select value={active} onChange={(event) => setSelected(event.target.value)}>{lists.map((list) => <option key={list.id} value={list.id}>{String(list.title)}</option>)}</select></label><label><span>{localized(language, "项目", "Item", "Elemento")}</span><input value={itemTitle} onChange={(event) => setItemTitle(event.target.value)} /></label><label className="check-field"><input type="checkbox" checked={surprise} onChange={(event) => setSurprise(event.target.checked)} /><span>{localized(language, "只有我能看到的惊喜准备", "Private surprise only I can see", "Sorpresa privada que solo yo veo")}</span></label><button onClick={addItem} disabled={!itemTitle}><Plus size={18} />{localized(language, "添加", "Add", "Añadir")}</button></div>
      <div className="relationship-rows">{items.filter((item) => item.listId === active).map((item) => <article key={item.id}><div><strong>{String(item.title)}</strong><span>{item.visibility === "private_surprise" ? localized(language, "私人惊喜", "Private surprise", "Sorpresa privada") : item.visibility === "revealed" ? localized(language, "已揭晓", "Revealed", "Revelada") : localized(language, "双方可见", "Shared", "Compartido")}</span></div>{item.visibility === "private_surprise" && <button onClick={() => reveal(item.id)}><Eye size={16} />{localized(language, "揭晓", "Reveal", "Revelar")}</button>}</article>)}</div></>}
    {notice && <p role="alert" className="relationship-notice">{notice}</p>}
  </section>;
}
