import { CheckCircle, Handshake, PaperPlaneRight, Plus, Sparkle } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { languageTag, localized, type Language } from "../../i18n";
import { jsonBody, relationshipApi } from "../relationship/api";
import type { GraphRecord, IssueDetail, RelationshipGraph } from "../relationship/types";

export function DecisionWorkspace({ language, userId, graph, onChanged }: { language: Language; userId: string; graph: RelationshipGraph; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(graph.issues[0]?.id || ""); const [detail, setDetail] = useState<IssueDetail | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState(""); const [category, setCategory] = useState("custom"); const [goal, setGoal] = useState(""); const [importance, setImportance] = useState(""); const [constraints, setConstraints] = useState(""); const [negotiables, setNegotiables] = useState(""); const [concerns, setConcerns] = useState(""); const [privateNotes, setPrivateNotes] = useState("");
  const load = async (id = selectedId) => { if (!id) { setDetail(null); return; } const result = await relationshipApi<IssueDetail>(`/api/issues/${id}`); setDetail(result); setSelectedId(id); };
  useEffect(() => { if (!selectedId && graph.issues[0]?.id) setSelectedId(graph.issues[0].id); }, [graph.issues, selectedId]);
  useEffect(() => { if (selectedId) void load(selectedId).catch((error) => setNotice(error.message)); }, [selectedId, graph]);
  const run = async (action: () => Promise<unknown>) => { setBusy(true); setNotice(""); try { await action(); await onChanged(); if (selectedId) await load(); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const createIssue = () => run(async () => { const result = await relationshipApi<{ issue: GraphRecord }>("/api/issues", jsonBody({ title, category })); setTitle(""); setSelectedId(result.issue.id); });
  const submitPerspective = () => run(() => relationshipApi(`/api/issues/${selectedId}/perspectives`, jsonBody({ goal, importance, constraints, negotiables, concerns, shareableText: [goal, importance, negotiables].filter(Boolean).join(" "), privateNotes, language })));
  const ownSummary = detail?.summaries.find((item) => item.ownerUserId === userId);
  const ownPerspective = detail?.perspectives.find((item) => item.ownerUserId === userId);
  const confirmSummary = () => run(() => relationshipApi(`/api/issues/${selectedId}/shareable-summary`, jsonBody({ text: ownSummary?.text })));
  const generate = () => run(() => relationshipApi(`/api/issues/${selectedId}/generate-options`, jsonBody({ language })));
  const evaluate = (proposalId: string, value: string) => run(() => relationshipApi(`/api/proposals/${proposalId}/evaluations`, jsonBody({ value })));
  const makeAgreement = (proposal: GraphRecord) => run(() => relationshipApi("/api/agreements", jsonBody({ sourceIssueId: selectedId, proposalId: proposal.id, title: proposal.title, summary: proposal.rationale, terms: [String(proposal.rationale || proposal.title)], reviewAt: new Date(Date.now() + 3 * 86400000).toISOString() })));
  const approve = (agreementId: string) => run(() => relationshipApi(`/api/agreements/${agreementId}/approve`, jsonBody({})));
  const createCommitment = (agreementId: string) => run(() => relationshipApi("/api/commitments", jsonBody({ agreementId, ownerType: "both", description: localized(language, "执行这份共同决定，并在三天后复盘。", "Follow through on this decision and review it in three days.", "Cumplir esta decisión y revisarla dentro de tres días."), dueAt: new Date(Date.now() + 2 * 86400000).toISOString(), reviewRequired: true })));
  const completeCommitment = (id: string) => run(() => relationshipApi(`/api/commitments/${id}/complete`, jsonBody({ completionEvidence: localized(language, "我确认自己负责的部分已经完成。", "I confirm my part is complete.", "Confirmo que completé mi parte.") })));
  const learnedPattern = localized(language, "在类似情境中，提前约定时间并复盘是有效的。", "In this situation, agreeing on a time in advance and reviewing it was helpful.", "En esta situación, acordar el momento con antelación y revisarlo fue útil.");
  const respondOutcome = (id: string) => run(() => relationshipApi(`/api/outcome-reviews/${id}/responses`, jsonBody({ actionCompleted: true, improvement: "improved", effective: localized(language, "提前约定并按时执行有帮助。", "Agreeing in advance and following through helped.", "Acordarlo con antelación y cumplirlo ayudó."), stillAccept: true, allowLearnedPattern: true, learnedPatternCandidate: learnedPattern })));
  const finalizeOutcome = (id: string) => run(() => relationshipApi(`/api/outcome-reviews/${id}/finalize`, jsonBody({})));

  return <section className="relationship-feature decision-workspace" aria-labelledby="decision-title"><header><div><Handshake size={24} /><h2 id="decision-title">{localized(language, "一起做决定", "Make a decision together", "Tomar una decisión juntos")}</h2></div><p>{localized(language, "观点先私下提交；只有你确认的摘要会进入共同 Agent。", "Perspectives start private. Only a summary you confirm enters the shared agent.", "Las perspectivas empiezan en privado. Solo el resumen que confirmes entra en el agente compartido.")}</p></header>
    <div className="relationship-form compact-grid"><label><span>{localized(language, "需要决定的事情", "What needs deciding", "Qué deben decidir")}</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={160} /></label><label><span>{localized(language, "类别", "Category", "Categoría")}</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="money">{localized(language, "金钱", "Money", "Dinero")}</option><option value="time">{localized(language, "时间", "Time", "Tiempo")}</option><option value="chores">{localized(language, "家务", "Chores", "Tareas domésticas")}</option><option value="family">{localized(language, "家庭", "Family", "Familia")}</option><option value="travel">{localized(language, "旅行", "Travel", "Viajes")}</option><option value="marriage">{localized(language, "婚姻", "Marriage", "Matrimonio")}</option><option value="custom">{localized(language, "其他", "Other", "Otro")}</option></select></label><button onClick={createIssue} disabled={busy || !title}><Plus size={18} />{localized(language, "创建决定房间", "Create decision room", "Crear sala de decisión")}</button></div>
    {graph.issues.length > 0 && <label className="issue-picker"><span>{localized(language, "当前议题", "Current issue", "Tema actual")}</span><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{graph.issues.map((issue) => <option key={issue.id} value={issue.id}>{String(issue.title)}</option>)}</select></label>}
    {detail && <div className="decision-flow">
      <section><span className="step-number">01</span><h3>{localized(language, "我的私人观点", "My private perspective", "Mi perspectiva privada")}</h3>{!ownPerspective ? <div className="perspective-form"><label><span>{localized(language, "我希望得到什么", "What I hope for", "Qué espero")}</span><textarea value={goal} onChange={(event) => setGoal(event.target.value)} /></label><label><span>{localized(language, "为什么重要", "Why it matters", "Por qué importa")}</span><textarea value={importance} onChange={(event) => setImportance(event.target.value)} /></label><label><span>{localized(language, "硬性约束", "Constraints", "Restricciones")}</span><textarea value={constraints} onChange={(event) => setConstraints(event.target.value)} /></label><label><span>{localized(language, "可以妥协", "Negotiables", "Aspectos negociables")}</span><textarea value={negotiables} onChange={(event) => setNegotiables(event.target.value)} /></label><label><span>{localized(language, "担心什么", "Concerns", "Preocupaciones")}</span><textarea value={concerns} onChange={(event) => setConcerns(event.target.value)} /></label><label><span>{localized(language, "完全私密，不进入共同 Agent", "Private only; never sent to the shared agent", "Solo privado; nunca se envía al agente compartido")}</span><textarea value={privateNotes} onChange={(event) => setPrivateNotes(event.target.value)} /></label><button onClick={submitPerspective} disabled={busy || !goal}><PaperPlaneRight size={18} />{localized(language, "提交给我的私人 Agent", "Submit to my private agent", "Enviar a mi agente privado")}</button></div> : <p className="completed-line"><CheckCircle size={18} weight="fill" />{localized(language, "私人观点已保存；对方看不到原文。", "Private perspective saved; your partner cannot see the original.", "Perspectiva privada guardada; tu pareja no puede ver el original.")}</p>}</section>
      {ownSummary && <section><span className="step-number">02</span><h3>{localized(language, "确认可共享摘要", "Confirm shareable summary", "Confirmar resumen compartible")}</h3><blockquote>{String(ownSummary.text)}</blockquote>{ownSummary.status === "draft" ? <button onClick={confirmSummary} disabled={busy}><CheckCircle size={18} />{localized(language, "允许共同 Agent 使用这段摘要", "Allow the shared agent to use this summary", "Permitir que el agente compartido use este resumen")}</button> : <p className="completed-line"><CheckCircle size={18} weight="fill" />{localized(language, "摘要已由我确认", "Summary confirmed by me", "Resumen confirmado por mí")}</p>}</section>}
      <section><span className="step-number">03</span><h3>{localized(language, "共同方案", "Shared options", "Opciones compartidas")}</h3>{detail.proposals.length === 0 ? <button onClick={generate} disabled={busy || detail.summaries.filter((item) => item.status === "confirmed").length < 2}><Sparkle size={18} />{localized(language, "双方确认摘要后生成方案", "Generate after both summaries are confirmed", "Generar cuando ambos resúmenes estén confirmados")}</button> : <div className="proposal-grid">{detail.proposals.map((proposal) => { const ownEvaluation = detail.evaluations.find((item) => item.proposalId === proposal.id && item.ownerUserId === userId); const evaluationCount = detail.evaluationCounts[proposal.id] || 0; return <article key={proposal.id}><strong>{String(proposal.title)}</strong><p>{String(proposal.rationale)}</p>{ownEvaluation ? <p className="completed-line"><CheckCircle size={16} weight="fill" />{localized(language, "我的评价已保存", "My evaluation is saved", "Mi evaluación está guardada")}</p> : <div className="row-actions"><button onClick={() => evaluate(proposal.id, "accept")}>{localized(language, "可以接受", "Accept", "Aceptar")}</button><button onClick={() => evaluate(proposal.id, "revise")}>{localized(language, "需要修改", "Revise", "Revisar")}</button></div>}<button className="text-action" disabled={evaluationCount < 2} onClick={() => makeAgreement(proposal)}>{evaluationCount < 2 ? localized(language, `等待双方分别评价（${evaluationCount}/2）`, `Waiting for both evaluations (${evaluationCount}/2)`, `Esperando ambas evaluaciones (${evaluationCount}/2)`) : localized(language, "以此起草 Agreement", "Draft an agreement from this", "Crear un acuerdo a partir de esto")}</button></article>; })}</div>}</section>
      {detail.agreements.map((agreement) => <section key={agreement.id}><span className="step-number">04</span><h3>{String(agreement.title)} · v{agreement.version}</h3><p>{String(agreement.summary)}</p><p className="status-line">{decisionLabel(language, String(agreement.status))}</p>{agreement.status === "awaiting_approvals" && <button onClick={() => approve(agreement.id)}><CheckCircle size={18} />{localized(language, "批准当前版本", "Approve this version", "Aprobar esta versión")}</button>}{agreement.status === "active" && <button onClick={() => createCommitment(agreement.id)}><Plus size={18} />{localized(language, "把决定变成 Commitment", "Turn this into a commitment", "Convertirlo en un compromiso")}</button>}</section>)}
      {graph.commitments.filter((item) => detail.agreements.some((agreement) => agreement.id === item.agreementId)).map((item) => <section key={item.id}><span className="step-number">05</span><h3>{localized(language, "正在执行", "In motion", "En marcha")}</h3><p>{String(item.description)}</p><p className="status-line">{decisionLabel(language, String(item.status))} · {decisionLabel(language, String(item.ownerType))}</p>{item.status === "active" && <button onClick={() => completeCommitment(item.id)}><CheckCircle size={18} />{localized(language, "确认我的部分完成", "Confirm my part complete", "Confirmar que completé mi parte")}</button>}</section>)}
      {graph.outcomes.filter((item) => detail.agreements.some((agreement) => agreement.id === item.agreementId)).map((item) => <section key={item.id}><span className="step-number">06</span><h3>{localized(language, "结果复盘", "Outcome review", "Revisión del resultado")}</h3><p>{new Date(String(item.reviewAt)).toLocaleString(languageTag(language))}</p>{item.status === "pending" && <div className="row-actions"><button onClick={() => respondOutcome(item.id)}>{localized(language, "提交我的复盘", "Submit my review", "Enviar mi revisión")}</button><button onClick={() => finalizeOutcome(item.id)}>{localized(language, "形成共同结果", "Finalize shared result", "Finalizar resultado compartido")}</button></div>}{item.status === "completed" && <p className="completed-line"><CheckCircle size={18} weight="fill" />{String(item.learnedPattern || localized(language, "复盘已完成", "Review complete", "Revisión completada"))}</p>}</section>)}
    </div>}
    {notice && <p role="alert" className="relationship-notice">{notice}</p>}
  </section>;
}

function decisionLabel(language: Language, value: string) { const labels: Record<string, [string, string, string]> = { awaiting_approvals: ["等待双方批准", "Awaiting both approvals", "Esperando ambas aprobaciones"], active: ["进行中", "Active", "Activo"], completed: ["已完成", "Completed", "Completado"], renegotiation_requested: ["请求重新协商", "Renegotiation requested", "Renegociación solicitada"], member_a: ["成员 A", "Member A", "Miembro A"], member_b: ["成员 B", "Member B", "Miembro B"], both: ["双方", "Both", "Ambos"] }; const label = labels[value]; return label ? localized(language, ...label) : value; }
