import { CheckCircle, Microphone, PaperPlaneRight, StopCircle } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { languageTag, localized, type Language } from "../../i18n";
import { KeyboardInput, KeyboardTextarea, useKeyboard } from "../../mobile";
import { useRealtimeTranscription } from "../../useRealtimeTranscription";
import type { GraphRecord } from "../relationship/types";

export type Member = { id: string; name: string; role: "A" | "B" };
export type DecisionMutation = (path: string, body: Record<string, unknown>, method?: string) => Promise<boolean>;
type ControlProps = { language: Language; userId: string; busy: boolean; mutate: DecisionMutation };
type Draft = { id?: string; title?: string; summary?: string; terms?: string[]; unresolvedPoints?: string[]; source?: string; confirmedAt?: string | null };
const strings = (value: unknown): string[] => Array.isArray(value) ? value.map(String) : [];

export function decisionLabel(language: Language, value: string) {
  const labels: Record<string, [string, string, string]> = {
    draft: ["需要重新协商", "Needs renegotiation", "Necesita renegociación"], awaiting_approvals: ["等待双方批准", "Awaiting both approvals", "Esperando ambas aprobaciones"], awaiting_confirmations: ["等待负责人确认", "Awaiting responsible people", "Esperando a las personas responsables"], active: ["进行中", "Active", "Activo"], completed: ["已完成", "Completed", "Completado"], cancelled: ["已拒绝 / 已取消", "Rejected / cancelled", "Rechazado / cancelado"], renegotiation_requested: ["请求重新协商", "Renegotiation requested", "Renegociación solicitada"], member_a: ["成员 A", "Member A", "Miembro A"], member_b: ["成员 B", "Member B", "Miembro B"], both: ["双方", "Both", "Ambos"], improved: ["有改善", "Improved", "Mejoró"], same: ["没有变化", "No change", "Sin cambios"], worse: ["更差了", "Worse", "Empeoró"], renegotiate: ["重新协商", "Renegotiate", "Renegociar"], continue: ["双方仍然接受", "Both still accept", "Ambos siguen aceptándolo"], not_shared: ["未授权共同展示", "Not shared", "No compartido"], mixed: ["体验不同，保留分歧", "Different experiences; disagreement remains", "Experiencias distintas; persiste el desacuerdo"], worse_reported: ["有人反馈效果更差", "A worse outcome was reported", "Se comunicó un peor resultado"], mutually_improved: ["双方都感到改善", "Both reported improvement", "Ambos comunicaron una mejora"],
  };
  return labels[value] ? localized(language, ...labels[value]) : value;
}

export function AgreementEditor({ language, draft, busy, onConfirm, confirmLabel }: { language: Language; draft: Draft; busy: boolean; onConfirm: (values: Record<string, unknown>) => Promise<boolean>; confirmLabel?: string }) {
  const keyboard = useKeyboard();
  const [title, setTitle] = useState(draft.title || ""), [summary, setSummary] = useState(draft.summary || ""), [terms, setTerms] = useState((draft.terms || []).join("\n")), [unresolved, setUnresolved] = useState((draft.unresolvedPoints || []).join("\n"));
  const [confirmed, setConfirmed] = useState(false);
  return <div className="decision-editor relationship-form">
    <label><span>{localized(language, "协议标题", "Agreement title", "Título del acuerdo")}</span><KeyboardInput value={title} onChange={(e) => { setTitle(e.target.value); setConfirmed(false); }} onBlur={() => keyboard.hide()} maxLength={160} /></label>
    <label><span>{localized(language, "共同说明", "Shared summary", "Resumen compartido")}</span><KeyboardTextarea value={summary} onChange={(e) => { setSummary(e.target.value); setConfirmed(false); }} onBlur={() => keyboard.hide()} maxLength={1200} rows={3} /></label>
    <label><span>{localized(language, "具体条款（每行一条）", "Concrete terms (one per line)", "Términos concretos (uno por línea)")}</span><KeyboardTextarea value={terms} onChange={(e) => { setTerms(e.target.value); setConfirmed(false); }} onBlur={() => keyboard.hide()} maxLength={4000} rows={4} /></label>
    <label><span>{localized(language, "仍未解决的问题（每行一条）", "Unresolved questions (one per line)", "Preguntas sin resolver (una por línea)")}</span><KeyboardTextarea value={unresolved} onChange={(e) => { setUnresolved(e.target.value); setConfirmed(false); }} onBlur={() => keyboard.hide()} maxLength={4000} rows={2} /></label>
    <label className="decision-consent"><KeyboardInput type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /><span>{localized(language, "我已核对以上文字，确认将它作为等待双方批准的新版本。", "I reviewed this text and confirm it as a new version awaiting both approvals.", "Revisé este texto y lo confirmo como nueva versión pendiente de ambas aprobaciones.")}</span></label>
    <p className="decision-hint">{localized(language, "确认草稿会使旧批准失效，相关承诺将等待重新协商。双方批准同一新版本后才生效。", "Confirming a draft invalidates old approvals and puts related commitments into renegotiation. It takes effect only after both approve the same new version.", "Confirmar el borrador invalida las aprobaciones anteriores y abre la renegociación de los compromisos relacionados. Solo entra en vigor cuando ambos aprueban la misma nueva versión.")}</p>
    <button disabled={busy || !confirmed || !title.trim() || !summary.trim() || !terms.trim()} onClick={() => void onConfirm({ title, summary, terms: terms.split("\n").filter((line) => line.trim()), unresolvedPoints: unresolved.split("\n").filter((line) => line.trim()), confirmed })}><CheckCircle size={18} />{confirmLabel || localized(language, "确认草稿，提交双方批准", "Confirm draft for both approvals", "Confirmar borrador para ambas aprobaciones")}</button>
  </div>;
}

export function SharedDiscussion({ issue, onChanged, ...props }: ControlProps & { issue: GraphRecord; onChanged: () => Promise<void> }) {
  const { language, userId, busy, mutate } = props; const keyboard = useKeyboard();
  const [text, setText] = useState(""), [voiceError, setVoiceError] = useState("");
  const messages = (issue.discussion || []) as Array<{ id: string; role: string; actorUserId?: string; text: string; source?: string }>;
  const draft = issue.discussionDraft as Draft | undefined;
  const voice = useRealtimeTranscription<{ issue: GraphRecord }>({ endpoint: `/api/issues/${issue.id}/${language}/realtime`, speakerId: userId, onCommitted: () => { setVoiceError(""); void onChanged(); }, onError: () => setVoiceError(localized(language, "语音暂时不可用，请检查麦克风权限或继续输入文字。", "Voice is unavailable. Check microphone permission or continue with text.", "La voz no está disponible. Revisa el permiso del micrófono o continúa por escrito.")) });
  useEffect(() => () => voice.stop(), [issue.id, language]);
  const send = async () => { if (!text.trim() || busy) return; if (await mutate(`/api/issues/${issue.id}/messages`, { text })) setText(""); };
  return <section className="decision-discussion" aria-label={localized(language, "共同对话", "Shared conversation", "Conversación compartida")}>
    <h3>{localized(language, "继续一起商量", "Keep talking together", "Seguir hablando juntos")}</h3>
    <p className="decision-hint">{localized(language, "这里的文字和语音会直接分享给对方。共同 Agent 只参考双方确认的摘要、共同协议和这里的对话。需要私下想清楚时，请返回私人空间。", "Text and voice here are shared directly with your partner. The shared Agent uses only both confirmed summaries, the shared agreement and this conversation. Return to your private space to think alone.", "El texto y la voz aquí se comparten directamente con tu pareja. El agente compartido usa solo ambos resúmenes confirmados, el acuerdo y esta conversación. Vuelve a tu espacio privado para pensar a solas.")}</p>
    <div className="decision-discussion-messages" aria-live="polite">{messages.map((message) => <article key={message.id} className={message.role === "assistant" ? "agent-message" : "owner-message"}><strong>{message.role === "assistant" ? message.source === "local" ? localized(language, "本地整理（AI 暂不可用）", "Local draft (AI unavailable)", "Borrador local (IA no disponible)") : "AI" : message.actorUserId === userId ? localized(language, "我", "Me", "Yo") : localized(language, "对方", "Partner", "Mi pareja")}</strong><p>{message.text}</p></article>)}</div>
    {voice.partial && <p role="status">{voice.partial.text || localized(language, "正在听…", "Listening…", "Escuchando…")}</p>}
    <div className="decision-shared-composer"><KeyboardTextarea value={text} onChange={(e) => setText(e.target.value)} onBlur={() => keyboard.hide()} placeholder={localized(language, "例如：试过后更累了，能改成每月一次吗？", "For example: This was exhausting. Could we try once a month?", "Por ejemplo: Fue agotador. ¿Podemos probar una vez al mes?")} maxLength={2000} rows={3} /><div className="row-actions"><button disabled={busy || voice.connecting} onClick={() => voice.listening ? voice.stop() : void voice.start()} aria-label={voice.listening ? localized(language, "停止共同语音", "Stop shared voice", "Detener voz compartida") : localized(language, "开始共同语音", "Start shared voice", "Iniciar voz compartida")}>{voice.listening ? <StopCircle size={20} /> : <Microphone size={20} />}{localized(language, "语音", "Voice", "Voz")}</button><button disabled={busy || !text.trim()} onClick={() => void send()}><PaperPlaneRight size={18} />{localized(language, "发送到共同对话", "Send to shared conversation", "Enviar a la conversación compartida")}</button></div></div>
    {voiceError && <p role="alert">{voiceError}</p>}
    {draft && !draft.confirmedAt && <aside className="decision-draft"><h4>{localized(language, "可编辑的新协议草稿", "Editable new agreement draft", "Nuevo borrador editable del acuerdo")}</h4><AgreementEditor key={draft.id} language={language} draft={draft} busy={busy} onConfirm={(values) => mutate(`/api/issues/${issue.id}/discussion-draft/confirm`, { ...values, version: issue.version, draftId: draft.id })} /></aside>}
  </section>;
}

export function AgreementCard({ agreement, approvals, members, ...props }: ControlProps & { agreement: GraphRecord; approvals: GraphRecord[]; members: Member[] }) {
  const { language, userId, busy, mutate } = props; const keyboard = useKeyboard();
  const [editing, setEditing] = useState(false), [reason, setReason] = useState(""), [planning, setPlanning] = useState(false);
  const approved = approvals.some((item) => item.agreementId === agreement.id && item.approvedVersion === agreement.version && item.ownerUserId === userId && !item.withdrawnAt);
  const pending = agreement.status === "awaiting_approvals", editable = pending || agreement.status === "draft";
  return <section className="decision-agreement" aria-label={String(agreement.title)}>
    <span className="step-number">04</span><h3>{String(agreement.title)} · v{agreement.version}</h3><p>{String(agreement.summary)}</p><ul>{strings(agreement.terms).map((term, index) => <li key={index}>{term}</li>)}</ul>
    {strings(agreement.unresolvedPoints).length > 0 && <p>{localized(language, "仍有分歧：", "Still unresolved: ", "Sin resolver: ")}{strings(agreement.unresolvedPoints).join(" · ")}</p>}
    <p className="status-line">{decisionLabel(language, agreement.status)}</p>
    {!!agreement.changeReason && <p>{localized(language, "变更说明：", "Reason for change: ", "Motivo del cambio: ")}{String(agreement.changeReason)}</p>}
    {pending && <button disabled={busy || approved} onClick={() => void mutate(`/api/agreements/${agreement.id}/approve`, { version: agreement.version })}><CheckCircle size={18} />{approved ? localized(language, "我已批准此版本，等待对方", "I approved this version; waiting for my partner", "Aprobé esta versión; esperando a mi pareja") : localized(language, "批准当前版本", "Approve this version", "Aprobar esta versión")}</button>}
    {(editable || agreement.status === "active") && <details className="decision-change-tools"><summary>{localized(language, "修改、拒绝或不再接受", "Revise, reject or withdraw acceptance", "Revisar, rechazar o retirar aceptación")}</summary><label><span>{localized(language, "给对方的说明（可选，会共享）", "Message to your partner (optional; shared)", "Mensaje para tu pareja (opcional; compartido)")}</span><KeyboardTextarea value={reason} onChange={(e) => setReason(e.target.value)} onBlur={() => keyboard.hide()} maxLength={1200} rows={2} /></label><div className="row-actions">{editable && <button disabled={busy} onClick={() => setEditing(!editing)}>{localized(language, "编辑条款", "Edit terms", "Editar términos")}</button>}<button disabled={busy} onClick={() => void mutate(`/api/agreements/${agreement.id}/request-change`, { version: agreement.version, reason })}>{localized(language, "请求重新协商", "Request renegotiation", "Solicitar renegociación")}</button><button disabled={busy} onClick={() => void mutate(`/api/agreements/${agreement.id}/reject`, { version: agreement.version, reason })}>{localized(language, "拒绝这份协议", "Reject this agreement", "Rechazar este acuerdo")}</button></div><p className="decision-hint">{localized(language, "请求重新协商或拒绝后，这份协议不再作为双方已接受的安排；任何新版本都需双方重新批准。", "Renegotiating or rejecting stops treating this agreement as mutually accepted. Any new version needs both approvals again.", "Renegociar o rechazar deja de considerar este acuerdo como aceptado por ambos. Toda nueva versión necesita ambas aprobaciones otra vez.")}</p></details>}
    {editing && editable && <AgreementEditor key={`${agreement.id}:${agreement.version}`} draft={agreement as Draft} language={language} busy={busy} onConfirm={async (values) => { const done = await mutate(`/api/agreements/${agreement.id}`, { ...values, version: agreement.version }, "PATCH"); if (done) setEditing(false); return done; }} />}
    {agreement.status === "active" && <><button disabled={busy} onClick={() => setPlanning(!planning)}>{localized(language, "安排具体承诺", "Plan a concrete commitment", "Planear un compromiso concreto")}</button>{planning && <CommitmentEditor {...props} members={members} agreement={agreement} onDone={() => setPlanning(false)} />}</>}
  </section>;
}

function CommitmentEditor({ agreement, members, onDone, ...props }: ControlProps & { agreement: GraphRecord; members: Member[]; onDone: () => void }) {
  const { language, busy, mutate } = props; const keyboard = useKeyboard();
  const [description, setDescription] = useState(""), [ownerType, setOwnerType] = useState(""), [dueAt, setDueAt] = useState(""), [reviewAt, setReviewAt] = useState(""), [confirmed, setConfirmed] = useState(false);
  const setField = (setter: (value: string) => void, value: string) => { setter(value); setConfirmed(false); };
  const valid = description.trim() && ownerType && dueAt && reviewAt && reviewAt >= dueAt;
  return <div className="decision-editor relationship-form" aria-label={localized(language, "承诺安排", "Commitment plan", "Plan del compromiso")}>
    <label><span>{localized(language, "具体做什么", "Concrete action", "Acción concreta")}</span><KeyboardTextarea value={description} onChange={(e) => setField(setDescription, e.target.value)} onBlur={() => keyboard.hide()} maxLength={600} rows={3} /></label>
    <label><span>{localized(language, "谁负责", "Who is responsible", "Quién es responsable")}</span><select value={ownerType} onChange={(e) => setField(setOwnerType, e.target.value)}><option value="">{localized(language, "请选择", "Choose", "Elige")}</option>{["A", "B"].map((role) => <option key={role} value={`member_${role.toLowerCase()}`}>{members.find((member) => member.role === role)?.name || decisionLabel(language, `member_${role.toLowerCase()}`)}</option>)}<option value="both">{localized(language, "双方各自确认自己的部分", "Both, each confirms their own part", "Ambos, cada uno confirma su parte")}</option></select></label>
    <label><span>{localized(language, "到期时间", "Due date", "Fecha límite")}</span><KeyboardInput type="datetime-local" value={dueAt} onChange={(e) => setField(setDueAt, e.target.value)} onBlur={() => keyboard.hide()} /></label>
    <label><span>{localized(language, "复盘时间", "Review date", "Fecha de revisión")}</span><KeyboardInput type="datetime-local" value={reviewAt} min={dueAt} onChange={(e) => setField(setReviewAt, e.target.value)} onBlur={() => keyboard.hide()} /></label>
    <label className="decision-consent"><KeyboardInput type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /><span>{localized(language, "我核对了内容、分工和日期，并确认自己负责的部分；对方负责的部分由 TA 另行确认。", "I reviewed the action, responsibility and dates, and confirm my own part. My partner confirms their own responsibility separately.", "Revisé la acción, responsabilidad y fechas, y confirmo mi parte. Mi pareja confirma su responsabilidad por separado.")}</span></label>
    <button disabled={busy || !confirmed || !valid} onClick={async () => { if (await mutate("/api/commitments", { agreementId: agreement.id, agreementVersion: agreement.version, description, ownerType, dueAt: new Date(dueAt).toISOString(), reviewAt: new Date(reviewAt).toISOString(), confirmed })) onDone(); }}>{localized(language, "确认承诺安排", "Confirm commitment plan", "Confirmar plan del compromiso")}</button>
  </div>;
}

export function CommitmentCard({ commitment, members, ...props }: ControlProps & { commitment: GraphRecord; members: Member[] }) {
  const { language, userId, busy, mutate } = props; const keyboard = useKeyboard();
  const [evidence, setEvidence] = useState("");
  const ownRole = members.find((member) => member.id === userId)?.role;
  const responsible = commitment.ownerType === "both" || commitment.ownerType === `member_${ownRole?.toLowerCase()}`;
  const ownConfirmed = strings(commitment.confirmedBy).includes(userId), ownCompleted = strings(commitment.completedBy).includes(userId);
  const ownerLabel = commitment.ownerType === "both" ? localized(language, "双方", "Both", "Ambos") : members.find((member) => `member_${member.role.toLowerCase()}` === commitment.ownerType)?.name || decisionLabel(language, String(commitment.ownerType));
  return <section className="decision-commitment"><span className="step-number">05</span><h3>{localized(language, "行动与跟进", "Action and follow-through", "Acción y seguimiento")}</h3><p>{String(commitment.description)}</p><p className="status-line">{decisionLabel(language, commitment.status)} · {ownerLabel}</p>
    <p>{localized(language, "到期：", "Due: ", "Vence: ")}{new Date(String(commitment.dueAt)).toLocaleString(languageTag(language))}<br />{localized(language, "复盘：", "Review: ", "Revisión: ")}{new Date(String(commitment.reviewAt)).toLocaleString(languageTag(language))}</p>
    {commitment.status === "awaiting_confirmations" && responsible && <button disabled={busy || ownConfirmed} onClick={() => void mutate(`/api/commitments/${commitment.id}/confirm`, { version: commitment.version })}>{ownConfirmed ? localized(language, "我已确认，等待另一位负责人", "I confirmed; waiting for the other person", "Confirmé; esperando a la otra persona") : localized(language, "我确认自己的责任和日期", "I confirm my responsibility and dates", "Confirmo mi responsabilidad y fechas")}</button>}
    {commitment.status === "active" && responsible && (ownCompleted ? <p className="completed-line">{localized(language, "我的部分已完成，等待对方确认自己的部分。", "My part is complete; waiting for my partner's part.", "Mi parte está completa; esperando la parte de mi pareja.")}</p> : <div className="relationship-form"><label><span>{localized(language, "完成说明（可选，会共享）", "Completion note (optional; shared)", "Nota de finalización (opcional; compartida)")}</span><KeyboardTextarea value={evidence} onChange={(e) => setEvidence(e.target.value)} onBlur={() => keyboard.hide()} maxLength={800} rows={2} /></label><button disabled={busy} onClick={() => void mutate(`/api/commitments/${commitment.id}/complete`, { version: commitment.version, completionEvidence: evidence })}><CheckCircle size={18} />{localized(language, "确认我的部分完成", "Confirm my part complete", "Confirmar que completé mi parte")}</button></div>)}
    {["active", "completed", "renegotiation_requested"].includes(commitment.status) && <button disabled={busy} onClick={() => void mutate(`/api/commitments/${commitment.id}/review`, { version: commitment.version })}>{localized(language, "现在复盘（未完成也可以）", "Review now (even if incomplete)", "Revisar ahora (aunque esté incompleto)")}</button>}
    {["active", "awaiting_confirmations"].includes(commitment.status) && <button disabled={busy} onClick={() => void mutate(`/api/commitments/${commitment.id}/renegotiate`, { version: commitment.version })}>{localized(language, "我需要重新协商这项承诺", "I need to renegotiate this commitment", "Necesito renegociar este compromiso")}</button>}
  </section>;
}

export function OutcomeCard({ outcome, response, members, ...props }: ControlProps & { outcome: GraphRecord; response?: GraphRecord; members: Member[] }) {
  const { language, busy, mutate } = props; const keyboard = useKeyboard();
  const [completed, setCompleted] = useState(""), [improvement, setImprovement] = useState(""), [accept, setAccept] = useState(""), [renegotiate, setRenegotiate] = useState(""), [effective, setEffective] = useState(""), [ineffective, setIneffective] = useState(""), [share, setShare] = useState(false), [learn, setLearn] = useState(false), [candidate, setCandidate] = useState("");
  const due = new Date(String(outcome.reviewAt)) <= new Date();
  const valid = completed && improvement && accept && renegotiate && (!learn || candidate.trim());
  const choices = [{ label: localized(language, "是否完成了自己负责的行动", "Did you complete your action?", "¿Completaste tu acción?"), value: completed, change: setCompleted }, { label: localized(language, "我现在仍然接受这份安排", "Do I still accept this arrangement?", "¿Sigo aceptando este acuerdo?"), value: accept, change: setAccept }, { label: localized(language, "我希望重新协商", "Do I want to renegotiate?", "¿Quiero renegociar?"), value: renegotiate, change: setRenegotiate }];
  const shared = (outcome.sharedResponses || []) as Array<{ ownerUserId: string; actionCompleted: boolean; improvement: string; effective: string; ineffective: string; stillAccept: boolean; renegotiate: boolean }>;
  const candidates = (outcome.learningCandidates || []) as Array<{ ownerUserId: string; text: string }>;
  return <section id={`outcome-review-${outcome.id}`} className="decision-outcome" aria-label={localized(language, "结果复盘", "Outcome review", "Revisión del resultado")}><span className="step-number">06</span><h3>{localized(language, "如实说说，实际怎么样", "How did it actually go?", "¿Cómo fue en realidad?")}</h3><p>{new Date(String(outcome.reviewAt)).toLocaleString(languageTag(language))}</p>
    {outcome.status === "pending" && !due && <p>{localized(language, "尚未到复盘时间；需要提前讨论时，可在承诺处选择“现在复盘”。", "This review is not due yet. Choose “Review now” on the commitment to start early.", "Aún no llegó la revisión. Elige «Revisar ahora» en el compromiso para empezar antes.")}</p>}
    {outcome.status === "pending" && due && !response && <div className="relationship-form decision-review-form">
      <p className="decision-hint">{localized(language, "如实记录，不必给出正面答案。默认仅自己可见；提交后双方只能知道你完成了复盘。", "Answer honestly; positive answers are not required. Your answers stay private by default. Submitting only lets your partner know you reviewed it.", "Responde con sinceridad; no hace falta una respuesta positiva. Tus respuestas son privadas por defecto. Enviarlas solo permite saber que completaste la revisión.")}</p>
      {choices.map((choice) => <label key={choice.label}><span>{choice.label}</span><select value={choice.value} onChange={(e) => choice.change(e.target.value)}><option value="">{localized(language, "请选择真实答案", "Choose your answer", "Elige tu respuesta")}</option><option value="yes">{localized(language, "是", "Yes", "Sí")}</option><option value="no">{localized(language, "否", "No", "No")}</option></select></label>)}
      <label><span>{localized(language, "实际效果", "Actual effect", "Efecto real")}</span><select value={improvement} onChange={(e) => setImprovement(e.target.value)}><option value="">{localized(language, "请选择真实答案", "Choose your answer", "Elige tu respuesta")}</option>{["improved", "same", "worse"].map((value) => <option key={value} value={value}>{decisionLabel(language, value)}</option>)}</select></label>
      <label><span>{localized(language, "哪些有帮助（可留空）", "What helped? (optional)", "¿Qué ayudó? (opcional)")}</span><KeyboardTextarea value={effective} onChange={(e) => setEffective(e.target.value)} onBlur={() => keyboard.hide()} maxLength={1000} rows={2} /></label>
      <label><span>{localized(language, "哪些没用或更难受（可留空）", "What failed or felt worse? (optional)", "¿Qué falló o te hizo sentir peor? (opcional)")}</span><KeyboardTextarea value={ineffective} onChange={(e) => setIneffective(e.target.value)} onBlur={() => keyboard.hide()} maxLength={1000} rows={3} /></label>
      <label className="decision-consent"><KeyboardInput type="checkbox" checked={share} onChange={(e) => setShare(e.target.checked)} /><span>{localized(language, "将以上回答明确分享给对方并允许共同 Agent 使用。", "Share these answers with my partner and allow the shared Agent to use them.", "Compartir estas respuestas con mi pareja y permitir que las use el agente compartido.")}</span></label>
      {!share && (accept === "no" || renegotiate === "yes") && <p className="decision-hint">{localized(language, "这份私人回答不会替你通知对方或改变共同协议。准备好后，请用协议上的“请求重新协商”明确告知。", "This private answer will not notify your partner of its contents or change the shared agreement. When ready, use “Request renegotiation” on the agreement.", "Esta respuesta privada no comunicará su contenido a tu pareja ni cambiará el acuerdo. Cuando quieras, usa «Solicitar renegociación» en el acuerdo.")}</p>}
      {candidates.length > 0 && <div className="decision-learning-candidates"><p>{localized(language, "对方允许分享的候选经验，可先编辑再决定是否同意：", "A proposed lesson shared with permission; edit it before deciding whether to agree:", "Experiencia propuesta con permiso para compartir; edítala antes de decidir si estás de acuerdo:")}</p>{candidates.map((item, index) => <button type="button" key={index} onClick={() => { setCandidate(item.text); setLearn(false); }}>{item.text}</button>)}</div>}
      <label><span>{localized(language, "可记住的经验草稿（可选，可编辑）", "Editable lesson draft (optional)", "Borrador editable de la experiencia (opcional)")}</span><KeyboardTextarea value={candidate} onChange={(e) => { setCandidate(e.target.value); setLearn(false); }} onBlur={() => keyboard.hide()} maxLength={600} rows={3} /></label>
      <label className="decision-consent"><KeyboardInput type="checkbox" checked={learn} onChange={(e) => setLearn(e.target.checked)} disabled={!candidate.trim()} /><span>{localized(language, "将这段经验候选分享给对方；只有双方都同意相同文字且确认有效时，才作为共同记忆。", "Share this proposed lesson with my partner. Remember it jointly only if both approve the same text and confirm it helped.", "Compartir esta experiencia propuesta con mi pareja. Recordarla juntos solo si ambos aprueban el mismo texto y confirman que ayudó.")}</span></label>
      <button disabled={busy || !valid} onClick={() => void mutate(`/api/outcome-reviews/${outcome.id}/responses`, { actionCompleted: completed === "yes", improvement, effective, ineffective, stillAccept: accept === "yes", renegotiate: renegotiate === "yes", shareResponse: share, allowLearnedPattern: learn, learnedPatternCandidate: candidate })}>{localized(language, "提交我的真实复盘", "Submit my honest review", "Enviar mi revisión sincera")}</button>
    </div>}
    {response && <aside className="decision-own-review"><strong>{localized(language, "我提交的回答", "My submitted answers", "Mis respuestas enviadas")}</strong><p>{decisionLabel(language, String(response.improvement))} · {response.actionCompleted ? localized(language, "已完成行动", "Action completed", "Acción completada") : localized(language, "行动未完成", "Action incomplete", "Acción incompleta")} · {response.stillAccept ? localized(language, "我仍接受", "I still accept", "Sigo aceptándolo") : localized(language, "我不再接受", "I no longer accept", "Ya no lo acepto")}</p>{!!response.effective && <p>{String(response.effective)}</p>}{!!response.ineffective && <p>{String(response.ineffective)}</p>}<small>{response.shareResponse ? localized(language, "已授权共同展示", "Shared with permission", "Compartido con permiso") : localized(language, "回答仅自己可见", "Answers private to me", "Respuestas privadas para mí")}</small></aside>}
    {outcome.status === "pending" && response && <><p className="decision-hint">{localized(language, `已收到 ${Number(outcome.responseCount || 1)}/2 份复盘；回答仍按各自授权展示。`, `${Number(outcome.responseCount || 1)}/2 reviews received; answers are shown only with each person's permission.`, `${Number(outcome.responseCount || 1)}/2 revisiones recibidas; las respuestas se muestran solo con permiso de cada persona.`)}</p><button disabled={busy || Number(outcome.responseCount || 0) < 2} onClick={() => void mutate(`/api/outcome-reviews/${outcome.id}/finalize`, {})}>{localized(language, "双方回答后形成共同结果", "Finalize after both have answered", "Finalizar cuando ambos respondan")}</button></>}
    {outcome.status === "completed" && <div><p className="completed-line"><CheckCircle size={18} />{localized(language, "双方已完成复盘", "Both reviews are complete", "Ambas revisiones están completas")}</p><p>{decisionLabel(language, String(outcome.mutualSatisfaction))} · {decisionLabel(language, String(outcome.nextAction))}</p>{shared.map((item) => <blockquote key={item.ownerUserId}><strong>{members.find((member) => member.id === item.ownerUserId)?.name || localized(language, "成员", "Member", "Miembro")}</strong><p>{decisionLabel(language, item.improvement)} · {item.actionCompleted ? localized(language, "已完成行动", "Action completed", "Acción completada") : localized(language, "行动未完成", "Action incomplete", "Acción incompleta")}</p>{item.effective && <p>{item.effective}</p>}{item.ineffective && <p>{item.ineffective}</p>}</blockquote>)}{!!outcome.learnedPattern && <p>{localized(language, "双方允许记住的经验：", "Lesson both agreed to remember: ", "Experiencia que ambos permitieron recordar: ")}{String(outcome.learnedPattern)}</p>}</div>}
  </section>;
}
