import { CheckCircle, Handshake, PaperPlaneRight, Plus, Sparkle } from "@phosphor-icons/react";
import { useEffect, useRef, useState } from "react";
import { localized, type Language } from "../../i18n";
import { KeyboardInput, KeyboardTextarea } from "../../mobile";
import { PrivateAgentWorkspace } from "../private-agent/PrivateAgentWorkspace";
import { jsonBody, relationshipApi } from "../relationship/api";
import type { GraphRecord, IssueDetail, RelationshipGraph } from "../relationship/types";
import { AgreementCard, CommitmentCard, OutcomeCard, SharedDiscussion, type Member } from "./DecisionControls";
import "./decisions.css";

export function DecisionWorkspace({ language, userId, graph, members = [], initialIssueId, initialOutcomeId, initialPrompt, onChanged }: { language: Language; userId: string; graph: RelationshipGraph; members?: Member[]; initialIssueId?: string | null; initialOutcomeId?: string | null; initialPrompt?: { text: string; nonce: number } | null; onChanged: () => Promise<void> }) {
  const [selectedId, setSelectedId] = useState(graph.issues[0]?.id || ""); const [detail, setDetail] = useState<IssueDetail | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState(""); const [category, setCategory] = useState("custom"); const [goal, setGoal] = useState(""); const [importance, setImportance] = useState(""); const [constraints, setConstraints] = useState(""); const [negotiables, setNegotiables] = useState(""); const [concerns, setConcerns] = useState(""); const [privateNotes, setPrivateNotes] = useState("");
  const [summaryText, setSummaryText] = useState("");
  const selectedTarget = useRef("");
  useEffect(() => {
    const targetKey = `${initialIssueId || ""}:${initialOutcomeId || ""}`;
    if (targetKey === selectedTarget.current) return;
    const outcome = graph.outcomes.find((item) => item.id === initialOutcomeId);
    const agreement = graph.agreements.find((item) => item.id === outcome?.agreementId);
    const targetId = initialIssueId || String(agreement?.sourceIssueId || "");
    if (targetId && graph.issues.some((item) => item.id === targetId)) { selectedTarget.current = targetKey; setSelectedId(targetId); }
  }, [initialIssueId, initialOutcomeId, graph]);
  useEffect(() => { if (detail && initialOutcomeId) requestAnimationFrame(() => document.getElementById(`outcome-review-${initialOutcomeId}`)?.scrollIntoView({ behavior: "smooth", block: "start" })); }, [detail?.issue.id, initialOutcomeId]);
  const load = async (id = selectedId) => { if (!id) { setDetail(null); return; } const result = await relationshipApi<IssueDetail>(`/api/issues/${id}`); setDetail(result); setSelectedId(id); };
  useEffect(() => { if (!selectedId && graph.issues[0]?.id) setSelectedId(graph.issues[0].id); }, [graph.issues, selectedId]);
  useEffect(() => { if (selectedId) void load(selectedId).catch((error) => setNotice(error.message)); }, [selectedId, graph]);
  const run = async (action: () => Promise<unknown>) => { if (busy) return false; setBusy(true); setNotice(""); try { await action(); await onChanged(); if (selectedId) await load(); return true; } catch (error) { const message = (error as Error).message; setNotice(language !== "zh" && /[\u4e00-\u9fff]/.test(message) ? localized(language, message, "This action could not be completed. Refresh and review the current state before trying again.", "No se pudo completar la acción. Actualiza y revisa el estado antes de reintentarlo.") : message); return false; } finally { setBusy(false); } };
  const mutate = (path: string, body: Record<string, unknown>, method = "POST") => run(() => relationshipApi(path, { ...jsonBody({ ...body, language }), method }));
  const createIssue = () => run(async () => { const result = await relationshipApi<{ issue: GraphRecord }>("/api/issues", jsonBody({ title, category })); setTitle(""); setSelectedId(result.issue.id); });
  const submitPerspective = () => run(() => relationshipApi(`/api/issues/${selectedId}/perspectives`, jsonBody({ goal, importance, constraints, negotiables, concerns, shareableText: [goal, importance, negotiables].filter(Boolean).join(" "), privateNotes, language })));
  const ownSummary = detail?.summaries.find((item) => item.ownerUserId === userId);
  const ownPerspective = detail?.perspectives.find((item) => item.ownerUserId === userId);
  useEffect(() => { setSummaryText(String(ownSummary?.text || "")); }, [ownSummary?.id, ownSummary?.version]);
  const confirmSummary = () => mutate(`/api/issues/${selectedId}/shareable-summary`, { text: summaryText });
  const generate = () => run(() => relationshipApi(`/api/issues/${selectedId}/generate-options`, jsonBody({ language })));
  const evaluate = (proposalId: string, value: string) => mutate(`/api/proposals/${proposalId}/evaluations`, { value });
  const makeAgreement = (proposal: GraphRecord) => mutate("/api/agreements", { sourceIssueId: selectedId, proposalId: proposal.id, title: proposal.title, summary: proposal.rationale, terms: [String(proposal.rationale || proposal.title)] });
  const controls = { language, userId, busy, mutate, members };

  return <section className="relationship-feature decision-workspace" aria-labelledby="decision-title"><header><div><Handshake size={24} /><h2 id="decision-title">{localized(language, "先想清楚，再一起决定", "Think privately, decide together", "Pensar en privado, decidir juntos")}</h2></div><p>{localized(language, "先只和你的 Agent 聊。你主动分享之后，对方才会第一次知道这个议题，并在自己的私密空间里思考。", "Start only with your Agent. Your partner first learns about the topic after you share it, then thinks in their own private space.", "Empieza solo con tu agente. Tu pareja conocerá el tema cuando lo compartas y lo pensará en su propio espacio privado.")}</p></header>
    <PrivateAgentWorkspace language={language} userId={userId} intentType="decision" threads={graph.privateAgentThreads} issueId={selectedId && !detail?.perspectives.some((item) => item.ownerUserId === userId) ? selectedId : undefined} initialPrompt={initialPrompt} onShared={async (id) => { setSelectedId(id); await onChanged(); }} onChanged={onChanged} />
    <details className="manual-tools"><summary>{localized(language, "手动编辑（备用）", "Manual editing (optional)", "Edición manual (opcional)")}</summary><div className="relationship-form compact-grid"><label><span>{localized(language, "需要决定的事情", "What needs deciding", "Qué deben decidir")}</span><KeyboardInput value={title} onChange={(event) => setTitle(event.target.value)} maxLength={160} /></label><label><span>{localized(language, "类别", "Category", "Categoría")}</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="money">{localized(language, "金钱", "Money", "Dinero")}</option><option value="time">{localized(language, "时间", "Time", "Tiempo")}</option><option value="chores">{localized(language, "家务", "Chores", "Tareas domésticas")}</option><option value="family">{localized(language, "家庭", "Family", "Familia")}</option><option value="travel">{localized(language, "旅行", "Travel", "Viajes")}</option><option value="marriage">{localized(language, "婚姻", "Marriage", "Matrimonio")}</option><option value="custom">{localized(language, "其他", "Other", "Otro")}</option></select></label><button onClick={createIssue} disabled={busy || !title}><Plus size={18} />{localized(language, "创建决定房间", "Create decision room", "Crear sala de decisión")}</button></div></details>
    {graph.issues.length > 0 && <label className="issue-picker"><span>{localized(language, "当前议题", "Current issue", "Tema actual")}</span><select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{graph.issues.map((issue) => <option key={issue.id} value={issue.id}>{String(issue.title)}</option>)}</select></label>}
    {detail && <div className="decision-flow">
      <section><span className="step-number">01</span><h3>{localized(language, "我的私人观点", "My private perspective", "Mi perspectiva privada")}</h3>{!ownPerspective ? <div className="perspective-form"><label><span>{localized(language, "我希望得到什么", "What I hope for", "Qué espero")}</span><KeyboardTextarea value={goal} onChange={(event) => setGoal(event.target.value)} /></label><label><span>{localized(language, "为什么重要", "Why it matters", "Por qué importa")}</span><KeyboardTextarea value={importance} onChange={(event) => setImportance(event.target.value)} /></label><label><span>{localized(language, "硬性约束", "Constraints", "Restricciones")}</span><KeyboardTextarea value={constraints} onChange={(event) => setConstraints(event.target.value)} /></label><label><span>{localized(language, "可以妥协", "Negotiables", "Aspectos negociables")}</span><KeyboardTextarea value={negotiables} onChange={(event) => setNegotiables(event.target.value)} /></label><label><span>{localized(language, "担心什么", "Concerns", "Preocupaciones")}</span><KeyboardTextarea value={concerns} onChange={(event) => setConcerns(event.target.value)} /></label><label><span>{localized(language, "完全私密，不进入共同 Agent", "Private only; never sent to the shared agent", "Solo privado; nunca se envía al agente compartido")}</span><KeyboardTextarea value={privateNotes} onChange={(event) => setPrivateNotes(event.target.value)} /></label><button onClick={submitPerspective} disabled={busy || !goal}><PaperPlaneRight size={18} />{localized(language, "提交给我的私人 Agent", "Submit to my private agent", "Enviar a mi agente privado")}</button></div> : <p className="completed-line"><CheckCircle size={18} weight="fill" />{localized(language, "私人观点已保存；对方看不到原文。", "Private perspective saved; your partner cannot see the original.", "Perspectiva privada guardada; tu pareja no puede ver el original.")}</p>}</section>
      {ownSummary && <section><span className="step-number">02</span><h3>{localized(language, "确认可共享摘要", "Confirm shareable summary", "Confirmar resumen compartible")}</h3><label><span>{localized(language, "可分享摘要（确认前可编辑）", "Shareable summary (editable before confirming)", "Resumen compartible (editable antes de confirmar)")}</span><KeyboardTextarea value={summaryText} onChange={(event) => setSummaryText(event.target.value)} readOnly={ownSummary.status !== "draft"} maxLength={1600} rows={4} /></label>{ownSummary.status === "draft" ? <button onClick={confirmSummary} disabled={busy || !summaryText.trim()}><CheckCircle size={18} />{localized(language, "允许共同 Agent 使用这段摘要", "Allow the shared agent to use this summary", "Permitir que el agente compartido use este resumen")}</button> : <p className="completed-line"><CheckCircle size={18} weight="fill" />{localized(language, "摘要已由我确认", "Summary confirmed by me", "Resumen confirmado por mí")}</p>}</section>}
      <section><span className="step-number">03</span><h3>{localized(language, "共同方案", "Shared options", "Opciones compartidas")}</h3>{detail.proposals.length === 0 ? <button onClick={generate} disabled={busy || detail.summaries.filter((item) => item.status === "confirmed").length < 2}><Sparkle size={18} />{localized(language, "双方确认摘要后生成方案", "Generate after both summaries are confirmed", "Generar cuando ambos resúmenes estén confirmados")}</button> : <div className="proposal-grid">{detail.proposals.map((proposal) => { const ownEvaluation = detail.evaluations.find((item) => item.proposalId === proposal.id && item.ownerUserId === userId); const evaluationCount = detail.evaluationCounts[proposal.id] || 0; return <article key={proposal.id}><strong>{String(proposal.title)}</strong><p>{String(proposal.rationale)}</p>{ownEvaluation ? <p className="completed-line"><CheckCircle size={16} weight="fill" />{localized(language, "我的评价已保存", "My evaluation is saved", "Mi evaluación está guardada")}</p> : <div className="row-actions"><button onClick={() => evaluate(proposal.id, "accept")}>{localized(language, "可以接受", "Accept", "Aceptar")}</button><button onClick={() => evaluate(proposal.id, "revise")}>{localized(language, "需要修改", "Revise", "Revisar")}</button></div>}<button className="text-action" disabled={evaluationCount < 2} onClick={() => makeAgreement(proposal)}>{evaluationCount < 2 ? localized(language, `等待双方分别评价（${evaluationCount}/2）`, `Waiting for both evaluations (${evaluationCount}/2)`, `Esperando ambas evaluaciones (${evaluationCount}/2)`) : localized(language, "以此起草 Agreement", "Draft an agreement from this", "Crear un acuerdo a partir de esto")}</button></article>; })}</div>}</section>
      {detail.summaries.filter((item) => item.status === "confirmed").length === 2 && <SharedDiscussion key={detail.issue.id} {...controls} issue={detail.issue} onChanged={async () => { await onChanged(); await load(); }} />}
      {detail.agreements.map((agreement) => <AgreementCard key={agreement.id} {...controls} agreement={agreement} approvals={graph.approvals} />)}
      {graph.commitments.filter((item) => detail.agreements.some((agreement) => agreement.id === item.agreementId)).map((item) => <CommitmentCard key={item.id} {...controls} commitment={item} />)}
      {graph.outcomes.filter((item) => detail.agreements.some((agreement) => agreement.id === item.agreementId)).map((item) => <OutcomeCard key={item.id} {...controls} outcome={item} response={graph.outcomeResponses.find((response) => response.outcomeId === item.id && response.ownerUserId === userId)} />)}
    </div>}
    {notice && <p role="alert" className="relationship-notice">{notice}</p>}
  </section>;
}
