import { useEffect, useState } from "react";
import { Heart, LockSimple } from "@phosphor-icons/react";
import { languageTag, localized } from "../../i18n";
import { KeyboardTextarea, useKeyboard } from "../../mobile";
import { jsonBody, relationshipApi } from "../relationship/api";
import { ShareComposer } from "../memories/ShareComposer";
import type { MemoryRecord, WorkspaceProps } from "../memories/types";
import "../memories/memory.css";

export function CheckinPanel({ language, userId, relationshipId = null, onChanged }: WorkspaceProps) {
  const [records, setRecords] = useState<MemoryRecord[]>([]); const [text, setText] = useState(""); const [kind, setKind] = useState("checkin"); const [mood, setMood] = useState("");
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(""); const [sharing, setSharing] = useState(""); const [deleting, setDeleting] = useState("");
  const keyboard = useKeyboard();
  const t = (zh: string, en: string, es: string) => localized(language, zh, en, es);
  const load = async () => { const result = await relationshipApi<{ checkins: MemoryRecord[] }>(`/api/checkins?language=${language}`); setRecords(result.checkins); };
  useEffect(() => {
    let active = true; setLoading(true); setRecords([]); setSharing(""); setNotice("");
    relationshipApi<{ checkins: MemoryRecord[] }>(`/api/checkins?language=${language}`).then((result) => { if (active) setRecords(result.checkins); }).catch((error) => { if (active) setNotice(error.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [language, userId, relationshipId]);
  const changed = async () => { await load(); await onChanged?.(); };
  const run = async (action: () => Promise<unknown>, success = "") => { setBusy(true); setNotice(""); try { await action(); await changed(); setNotice(success); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const kindLabel = (value: string) => value === "gratitude" ? t("一句感谢", "A little gratitude", "Un agradecimiento") : value === "good_moment" ? t("一个好时刻", "A good moment", "Un buen momento") : t("此刻的我", "How I am", "Cómo estoy");
  const moodLabel = (value: string) => value === "low" ? t("有点低落", "Feeling low", "Con poco ánimo") : value === "mixed" ? t("说不清", "Mixed feelings", "Sentimientos encontrados") : value === "okay" ? t("还好", "Doing okay", "Estoy bien") : t("心情不错", "Feeling good", "Con buen ánimo");
  return <section className="relationship-feature memory-workspace checkin-workspace" aria-labelledby="checkin-title">
    <header><div><Heart size={24} /><h2 id="checkin-title">{t("留一句此刻的话", "A few words for this moment", "Unas palabras para este momento")}</h2></div><p>{t("不必每天来，也不必感觉很好。你可以只为自己写，或留下一句感谢、一个好时刻。", "No daily streak and no need to feel good. Write just for yourself, a little gratitude, or a good moment.", "Sin rachas diarias ni obligación de estar bien. Escribe para ti, un agradecimiento o un buen momento.")}</p></header>
    <form className="memory-composer" onSubmit={(event) => { event.preventDefault(); void run(async () => { await relationshipApi("/api/checkins", jsonBody({ text, kind, mood: mood || null, language })); setText(""); setMood(""); }, t("已私下保存。只有你能看到。", "Saved privately. Only you can see it.", "Guardado en privado. Solo tú puedes verlo.")); }}>
      <div className="checkin-options"><label><span>{t("想留下什么", "What to keep", "Qué guardar")}</span><select value={kind} onChange={(event) => setKind(event.target.value)}>{["checkin", "gratitude", "good_moment"].map((value) => <option value={value} key={value}>{kindLabel(value)}</option>)}</select></label><label><span>{t("心情（可不选，只对你可见）", "Mood (optional, private)", "Ánimo (opcional, privado)")}</span><select value={mood} onChange={(event) => setMood(event.target.value)}><option value="">{t("先不描述", "Leave it open", "No describirlo")}</option>{["low", "mixed", "okay", "good"].map((value) => <option value={value} key={value}>{moodLabel(value)}</option>)}</select></label></div>
      <label><span>{t("用自己的话说一句", "In your own words", "Con tus propias palabras")}</span><KeyboardTextarea onBlur={() => keyboard.hide()} value={text} onChange={(event) => setText(event.target.value)} maxLength={2000} placeholder={kind === "gratitude" ? t("今天有一件小事，我很感谢…", "One small thing I appreciated today…", "Un pequeño gesto que agradecí hoy…") : kind === "good_moment" ? t("有一刻，我想记下来…", "A moment I would like to keep…", "Un momento que quisiera guardar…") : t("此刻我觉得…", "Right now, I feel…", "Ahora mismo siento…")} /></label>
      <p className="memory-provenance">{t("不会自动分享，也不会自动交给 AI。", "No automatic sharing or AI use.", "No se comparte ni se envía a la IA automáticamente.")}</p><button type="submit" disabled={busy || !text.trim()}><LockSimple size={17} />{t("只为自己保存", "Save just for me", "Guardar solo para mí")}</button>
    </form>
    <div className="memory-toolbar"><h3>{t("留下的时刻", "Moments kept", "Momentos guardados")}</h3><button className="memory-quiet" disabled={busy} onClick={() => void run(async () => {})}>{t("刷新", "Refresh", "Actualizar")}</button></div>
    {loading ? <p role="status">{t("正在找回这些时刻…", "Loading your moments…", "Cargando tus momentos…")}</p> : records.length === 0 ? <p className="memory-empty">{t("这里还很安静。什么时候想写一句，都可以。", "It is quiet here for now. Leave a few words whenever you want.", "Por ahora hay calma aquí. Deja unas palabras cuando quieras.")}</p> : <ol className="memory-timeline">{records.map((record) => <li key={record.id}><article className="memory-entry"><div className="memory-meta"><span>{record.visibility === "private" ? t("只有我可见", "Only me", "Solo yo") : t("本人确认的分享 · 双方可见", "Owner-confirmed share · Visible to both", "Compartido por su autor · Visible para ambos")}</span><time dateTime={record.createdAt}>{new Date(record.createdAt).toLocaleString(languageTag(language))}</time></div><h4>{kindLabel(record.kind)}</h4><p className="memory-text">{record.text}</p>{record.visibility === "private" && record.ownerUserId === userId && <>{record.mood && <p className="memory-provenance">{t("我的私人心情", "My private mood", "Mi ánimo privado")} · {moodLabel(record.mood)}</p>}<div className="memory-actions">{relationshipId && <button className="memory-quiet" disabled={busy} onClick={() => setSharing(sharing === record.id ? "" : record.id)}>{t("准备一段分享", "Prepare a share", "Preparar un texto para compartir")}</button>}<button className="memory-quiet" disabled={busy} onClick={() => setDeleting(record.id)}>{t("删除私人原文", "Delete private original", "Borrar original privado")}</button></div>{deleting === record.id && <div className="memory-delete"><p>{t("删除私人原文不会删除已经分享的副本。", "Deleting your private original does not delete shared copies.", "Borrar tu original privado no borra las copias compartidas.")}</p><button disabled={busy} onClick={() => void run(async () => { await relationshipApi(`/api/checkins/${record.id}`, { method: "DELETE", body: JSON.stringify({ expectedVersion: record.version, language }) }); setDeleting(""); })}>{t("确认删除", "Confirm deletion", "Confirmar eliminación")}</button><button className="memory-quiet" onClick={() => setDeleting("")}>{t("取消", "Cancel", "Cancelar")}</button></div>}{sharing === record.id && <ShareComposer key={`${record.id}:${record.version}`} record={record} collection="checkins" language={language} onShared={changed} onClose={() => setSharing("")} />}</>}</article></li>)}</ol>}
    {notice && <p role="status" className="relationship-notice">{notice}</p>}
  </section>;
}
