import { Bell, CalendarBlank, Plus } from "@phosphor-icons/react";
import { useState } from "react";
import { languageTag, localized, type Language } from "../../i18n";
import { jsonBody, relationshipApi } from "../relationship/api";
import type { GraphRecord } from "../relationship/types";

export function MilestonesPanel({ language, milestones, reminders, onChanged, onRemind }: { language: Language; milestones: GraphRecord[]; reminders: GraphRecord[]; onChanged: () => Promise<void>; onRemind?: (id: string, title: string) => void }) {
  const [title, setTitle] = useState(""); const [date, setDate] = useState(""); const [type, setType] = useState("anniversary"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const create = async () => { if (!title || !date) return; setBusy(true); try { await relationshipApi("/api/milestones", jsonBody({ title, date, type, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, recurringRule: type === "birthday" || type === "anniversary" ? "yearly" : "once" })); setTitle(""); setDate(""); await onChanged(); setNotice(""); } catch (error) { setNotice((error as Error).message); } finally { setBusy(false); } };
  const remind = async (id: string, visibility: "private" | "shared") => { try { await relationshipApi(`/api/milestones/${id}/reminders`, jsonBody({ visibility, minutesBefore: 14 * 24 * 60, privateNotes: visibility === "private" ? localized(language, "为这一天做准备", "Prepare for this day", "Prepararme para este día") : "" })); await onChanged(); setNotice(""); } catch (error) { setNotice((error as Error).message); } };
  return <section className="relationship-feature" aria-labelledby="milestones-title"><header><div><CalendarBlank size={23} /><h2 id="milestones-title">{localized(language, "重要日子", "Milestones", "Fechas importantes")}</h2></div><p>{localized(language, "共同日期双方可见；准备提醒可以只属于你。", "Shared dates are visible to both; preparation reminders can stay yours.", "Las fechas compartidas son visibles para ambos; tus recordatorios de preparación pueden ser privados.")}</p></header>
    <div className="relationship-form compact-grid"><label><span>{localized(language, "名称", "Title", "Título")}</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} /></label><label><span>{localized(language, "日期", "Date", "Fecha")}</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label><span>{localized(language, "类型", "Type", "Tipo")}</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="anniversary">{localized(language, "周年", "Anniversary", "Aniversario")}</option><option value="birthday">{localized(language, "生日", "Birthday", "Cumpleaños")}</option><option value="trip">{localized(language, "旅行", "Trip", "Viaje")}</option><option value="custom">{localized(language, "自定义", "Custom", "Personalizado")}</option></select></label><button type="button" onClick={create} disabled={busy || !title || !date}><Plus size={18} />{localized(language, "添加", "Add", "Añadir")}</button></div>
    {notice && <p role="alert" className="relationship-notice">{notice}</p>}
    <div className="relationship-rows">{milestones.length ? milestones.map((item) => <article key={item.id} id={`milestone-${item.id}`}><div><strong>{String(item.title)}</strong><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString(languageTag(language))} · {item.recurringRule === "yearly" ? localized(language, "每年", "Yearly", "Anual") : localized(language, "单次", "Once", "Una vez")}</span></div><div className="row-actions">{onRemind && <button onClick={() => onRemind(item.id, String(item.title || ""))}><Bell size={16} />{localized(language, "选择我的提醒时间", "Choose my reminder time", "Elegir la hora de mi recordatorio")}</button>}<button onClick={() => remind(item.id, "private")}><Bell size={16} />{localized(language, "私人准备", "Private reminder", "Recordatorio privado")}</button><button onClick={() => remind(item.id, "shared")}><Bell size={16} />{localized(language, "共同提醒", "Shared reminder", "Recordatorio compartido")}</button></div><small>{localized(language, "我的提醒", "My reminders", "Mis recordatorios")}: {reminders.filter((reminder) => reminder.milestoneId === item.id).length}</small></article>) : <p className="relationship-empty">{localized(language, "还没有共同日期。", "No shared dates yet.", "Aún no hay fechas compartidas.")}</p>}</div>
  </section>;
}
