import { useEffect, useRef, useState } from "react";
import { DownloadSimple, ShieldCheck } from "@phosphor-icons/react";
import { languageTag, localized, type Language } from "../../i18n";
import { KeyboardInput, useKeyboard } from "../../mobile";
import { jsonBody, relationshipApi } from "../relationship/api";
import "./privacy.css";

type Summary = { id: string; relationshipId?: string; issueId: string; text: string; version: number; status: string; aiAccessScope: string; withdrawnAt: string | null };
type PrivacyData = { privateRetentionDays: number | null; recoveryEnabled: boolean; privateCount: number; relationships: Array<{ id: string; status: string }>; sharedSummaries: Summary[]; consentHistory: Array<{ eventType: string; createdAt: string; sourceVersion?: number }> };
type PendingAction = { kind: "retention" | "recovery" | "export" | "delete-private" | "leave" | "account"; days?: number | null } | { kind: "withdraw"; summary: Summary };
type PrivacyProps = { language: Language; onChanged: () => void | Promise<void>; onLeft: () => void | Promise<void>; onDeleted: () => void | Promise<void> };

function downloadFile(contents: string, filename: string, type: string) {
  const url = URL.createObjectURL(new Blob([contents], { type }));
  const link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function PrivacySettings({ language, onChanged, onLeft, onDeleted }: PrivacyProps) {
  const [data, setData] = useState<PrivacyData | null>(null); const [days, setDays] = useState("keep");
  const [pending, setPending] = useState<PendingAction | null>(null); const [password, setPassword] = useState(""); const [confirmed, setConfirmed] = useState(false);
  const [recoveryCode, setRecoveryCode] = useState(""); const [showCode, setShowCode] = useState(false);
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const confirmationRef = useRef<HTMLElement>(null);
  const keyboard = useKeyboard(); const t = (zh: string, en: string, es: string) => localized(language, zh, en, es);
  const load = async () => { const result = await relationshipApi<PrivacyData>(`/api/privacy?language=${language}`); setData(result); setDays(result.privateRetentionDays === null ? "keep" : String(result.privateRetentionDays)); };
  useEffect(() => { let active = true; setLoading(true); relationshipApi<PrivacyData>(`/api/privacy?language=${language}`).then((result) => { if (active) { setData(result); setDays(result.privateRetentionDays === null ? "keep" : String(result.privateRetentionDays)); } }).catch((error) => { if (active) setNotice(error.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [language]);
  useEffect(() => { if (pending) { confirmationRef.current?.scrollIntoView({ block: "start", behavior: "smooth" }); confirmationRef.current?.focus({ preventScroll: true }); } }, [pending]);
  const prepare = (action: PendingAction) => { keyboard.hide(); setPending(action); setPassword(""); setConfirmed(false); setNotice(""); };
  const cancel = () => { keyboard.hide(); setPending(null); setPassword(""); setConfirmed(false); };
  const period = (value: number | null) => value === null ? t("由我手动删除", "Until I delete manually", "Hasta que los borre manualmente") : t(`${value}天未更新后删除`, `Delete after ${value} days without updates`, `Borrar tras ${value} días sin cambios`);
  const actionTitle = (action: PendingAction) => ({ retention: t("确认私人内容保留期限", "Confirm private retention", "Confirmar conservación privada"), recovery: t("生成新恢复码", "Generate a new recovery code", "Generar un nuevo código"), export: t("下载我的数据副本", "Download my data copy", "Descargar copia de mis datos"), "delete-private": t("永久删除我的私人内容", "Permanently delete my private content", "Borrar permanentemente mi contenido privado"), leave: t("退出当前关系", "Leave this relationship", "Salir de esta relación"), account: t("永久删除我的账号", "Permanently delete my account", "Borrar mi cuenta permanentemente"), withdraw: t("停止共同 AI 使用这段摘要", "Stop joint AI use of this summary", "Detener el uso de este resumen por la IA compartida") })[action.kind];
  const actionDescription = (action: PendingAction) => {
    if (action.kind === "retention") return t(`新规则：${period(action.days ?? null)}。仅影响你的私人 Agent 对话、私人记忆和轻量记录；后台清理后无法恢复。共享副本、共同协议、提醒、其他私人观点与同意记录不在此规则内。`, `New rule: ${period(action.days ?? null)}. This applies only to your private Agent conversations, private memories, and check-ins. Background deletion cannot be undone. Shared copies, agreements, reminders, other private perspectives, and consent records are outside this rule.`, `Nueva regla: ${period(action.days ?? null)}. Solo afecta tus conversaciones privadas con el agente, recuerdos privados y registros cotidianos. La limpieza es irreversible. Las copias compartidas, acuerdos, recordatorios, otras perspectivas privadas y registros de consentimiento quedan fuera.`);
    if (action.kind === "recovery") return t("新码会立即使旧恢复码失效。服务器只保存校验值；完整新码只在本次页面显示，请保存到安全位置。", "The new code immediately replaces the old one. The server stores only a verification hash. The full new code appears only here; save it securely.", "El nuevo código invalida de inmediato el anterior. El servidor solo guarda un valor de verificación. El código completo solo aparece aquí; guárdalo en un lugar seguro.");
    if (action.kind === "export") return t("下载你可访问的数据副本，包含自己的私人内容与获准可见的共同记录，不包含伴侣的私人原文。文件可能含敏感文字，请选择安全的保存位置。", "Download your accessible data, including your private content and shared records you may access. Your partner’s private originals are excluded. The file may contain sensitive text; save it securely.", "Descarga tus datos accesibles, incluidos tu contenido privado y los registros compartidos autorizados. Se excluyen los originales privados de tu pareja. El archivo puede contener texto sensible; guárdalo de forma segura.");
    if (action.kind === "delete-private") return t("删除你自己的私人图记录（含私聊、私人观点与复盘、记忆、心情、私人提醒和惊喜）以及房间中的私人 AI 分析。账号、共同记录、公开对话原话、同意历史和投递设置保留。此操作无法撤销，也不会让对方忘记已读内容。", "Delete your private records, including Agent chats, perspectives, reviews, memories, moods, private reminders and surprises, plus private room AI analysis. Your account, shared records, public conversation text, consent history, and delivery settings stay. This cannot be undone or erase what your partner already read.", "Borra tus registros privados: conversaciones con el agente, perspectivas, revisiones, recuerdos, ánimo, recordatorios privados y sorpresas, además del análisis privado de IA en salas. Se conservan tu cuenta, registros compartidos, texto público, historial de consentimiento y ajustes de entrega. Es irreversible y no borra lo que tu pareja ya leyó.");
    if (action.kind === "leave") return t("无需对方批准。双方将结束当前绑定并失去旧关系的实时访问；旧共同记录保留，可在数据导出中取得。你的私人对话、记忆和轻量记录保留在个人空间，停止 AI 使用。退出不会删除对方的内容或撤销已达成的共同协议。", "No partner approval is needed. The pairing ends for both people, and live access to this relationship closes. Shared history remains available through data export. Your private Agent chats, memories, and check-ins stay in your personal space with AI use stopped. Leaving does not delete your partner’s content or undo agreed commitments.", "No necesitas la aprobación de tu pareja. El vínculo termina para ambos y se cierra el acceso en vivo. El historial compartido sigue disponible en la exportación. Tus conversaciones privadas, recuerdos y registros quedan en tu espacio personal sin uso de IA. Salir no borra el contenido de tu pareja ni revoca los acuerdos alcanzados.");
    if (action.kind === "account") return t("删除账号会结束关系绑定、撤销全部登录、移除你的私人内容及房间中的本人原话，并匿名化账号身份。双方共同记录、已经确认的协议和最小同意审计仍会保留；不能清空对方的数据或抹除已读内容。删除后不能用恢复码找回账号，建议先下载副本。", "This ends the pairing, signs out all sessions, removes your private content and your original room messages, and anonymizes your identity. Shared records, confirmed agreements, and minimal consent audit remain. It cannot erase your partner’s data or what they already read. Recovery codes cannot restore a deleted account; consider downloading your copy first.", "Se termina el vínculo, se cierran todas las sesiones, se borra tu contenido privado y tus mensajes originales en salas, y se anonimiza tu identidad. Se conservan los registros compartidos, acuerdos confirmados y auditoría mínima de consentimiento. No borra datos de tu pareja ni lo ya leído. El código no recupera una cuenta borrada; considera descargar antes una copia.");
    return t("只撤回这段摘要的未来共同 AI 使用授权；现有候选方案会失效，需要重新生成。已经确认的共同协议保持有效。已分享的摘要仍可查看，无法收回对方已经读过的内容。", "This withdraws future joint AI use of this summary. Existing candidate options are invalidated and must be generated again. Confirmed agreements stay valid. The shared summary remains visible; text already read cannot be taken back.", "Retira el uso futuro de este resumen por la IA compartida. Las opciones propuestas dejan de ser válidas y deben generarse de nuevo. Los acuerdos confirmados siguen vigentes. El resumen compartido sigue visible; no se puede retirar lo ya leído.");
  };
  const execute = async () => {
    if (!pending || !confirmed) return; const action = pending; setBusy(true); setNotice(""); keyboard.hide();
    try {
      const body = { password, confirm: true, language };
      if (action.kind === "retention") await relationshipApi("/api/privacy", { method: "PATCH", body: JSON.stringify({ ...body, privateRetentionDays: action.days ?? null }) });
      if (action.kind === "recovery") { const result = await relationshipApi<{ recoveryCode: string }>("/api/privacy/recovery-code", jsonBody(body)); setRecoveryCode(result.recoveryCode); setShowCode(false); }
      if (action.kind === "export") { const result = await relationshipApi<unknown>("/api/privacy/export", jsonBody(body)); downloadFile(JSON.stringify(result, null, 2), "toward-us-export.json", "application/json;charset=utf-8"); }
      if (action.kind === "delete-private") await relationshipApi("/api/privacy/delete-private", jsonBody(body));
      if (action.kind === "leave") { await relationshipApi("/api/privacy/leave", jsonBody(body)); setRecoveryCode(""); await onLeft(); }
      if (action.kind === "account") { await relationshipApi("/api/privacy/account", { method: "DELETE", body: JSON.stringify(body) }); setRecoveryCode(""); await onDeleted(); setPending(null); return; }
      if (action.kind === "withdraw") await relationshipApi(`/api/privacy/summaries/${action.summary.id}/withdraw`, jsonBody({ confirm: true, language, version: action.summary.version }));
      setPending(null); await load(); await onChanged(); setNotice(action.kind === "export" ? t("数据文件已交给浏览器下载。", "Your browser received the data file for download.", "El navegador recibió el archivo para descargar.") : t("操作已完成。", "Done.", "Operación completada."));
    } catch (error) { setNotice((error as Error).message); }
    finally { setBusy(false); setPassword(""); setConfirmed(false); }
  };
  const summaryIsCurrent = (summary: Summary) => Boolean(summary.relationshipId && data?.relationships.some((relationship) => relationship.id === summary.relationshipId && relationship.status === "active"));
  return <section className="relationship-feature privacy-workspace" aria-labelledby="privacy-title">
    <header><ShieldCheck size={24} /><h2 id="privacy-title">{t("隐私与我的账号", "Privacy and my account", "Privacidad y mi cuenta")}</h2></header><p>{t("你决定哪些内容留在个人空间、哪些内容交给 AI。退出关系或管理自己的数据，不需要伴侣批准。", "You decide what stays private and what AI may use. Leaving a relationship or managing your own data does not require your partner’s approval.", "Tú decides qué queda privado y qué puede usar la IA. Salir de una relación o gestionar tus datos no requiere la aprobación de tu pareja.")}</p>
    {loading ? <p role="status">{t("正在读取你的隐私设置…", "Loading your privacy settings…", "Cargando tus ajustes de privacidad…")}</p> : !data ? <button disabled={busy} onClick={() => { setLoading(true); void load().catch((error) => setNotice(error.message)).finally(() => setLoading(false)); }}>{t("重新加载", "Reload", "Volver a cargar")}</button> : <>
      <section className="privacy-section"><h3>{t("私人内容保留多久", "How long private content stays", "Cuánto tiempo se conserva lo privado")}</h3><p>{t("自动清理只覆盖私人 Agent 对话、私人记忆和轻量记录，按最后更新时间计算。未设置期限时，由你手动删除。", "Automatic cleanup covers only private Agent conversations, private memories, and check-ins, based on the last update. Without a time limit, you delete them manually.", "La limpieza automática solo incluye conversaciones privadas con el agente, recuerdos privados y registros cotidianos, desde su última modificación. Sin límite, los borras manualmente.")}</p><label><span>{t("保留规则", "Retention rule", "Regla de conservación")}</span><select value={days} onChange={(event) => setDays(event.target.value)}><option value="keep">{period(null)}</option>{[7, 30, 90, 365].map((value) => <option key={value} value={value}>{period(value)}</option>)}</select></label><button disabled={busy || (days === "keep" ? null : Number(days)) === data.privateRetentionDays} onClick={() => prepare({ kind: "retention", days: days === "keep" ? null : Number(days) })}>{t("检查并保存规则", "Review and save rule", "Revisar y guardar regla")}</button></section>
      <section className="privacy-section"><h3>{t("账号找回", "Account recovery", "Recuperación de cuenta")}</h3><p>{data.recoveryEnabled ? t("已有有效恢复码。若丢失，可生成新码；旧码会立即失效。", "A recovery code is active. Generate a replacement if it is lost; the old code will stop working immediately.", "Hay un código activo. Si lo perdiste, genera otro; el anterior dejará de funcionar de inmediato.") : t("还没有有效恢复码。邮箱找回尚未开通，请先生成并妥善保存一次性恢复码。", "No recovery code is active. Email recovery is not available yet. Generate and securely save a one-time recovery code.", "No hay un código activo. La recuperación por correo aún no está disponible. Genera y guarda de forma segura un código de un solo uso.")}</p><button disabled={busy} onClick={() => prepare({ kind: "recovery" })}>{data.recoveryEnabled ? t("更换恢复码", "Replace recovery code", "Reemplazar código") : t("生成恢复码", "Generate recovery code", "Generar código")}</button>
        {recoveryCode && <div className="privacy-recovery-code" role="status"><strong>{t("新恢复码只在本次页面显示", "Your new code is available only on this page", "Tu nuevo código solo está disponible en esta página")}</strong><p>{t("保存到密码管理器或其他安全位置。关闭显示或离开页面后，这里无法再次查看完整码。", "Save it in a password manager or another secure place. After dismissing it or leaving this page, the full code cannot be shown again.", "Guárdalo en un gestor de contraseñas u otro lugar seguro. Después de cerrarlo o salir, no se podrá mostrar completo de nuevo.")}</p>{showCode ? <code>{recoveryCode}</code> : <p>{t("恢复码已隐藏", "Recovery code is hidden", "El código está oculto")}</p>}<div className="privacy-actions"><button className="privacy-quiet" onClick={() => setShowCode(!showCode)}>{showCode ? t("暂时隐藏", "Hide for now", "Ocultar por ahora") : t("显示恢复码", "Show recovery code", "Mostrar código")}</button><button onClick={() => downloadFile(`${t("Toward Us 一次性恢复码。请安全保存。", "Toward Us one-time recovery code. Store securely.", "Código Toward Us de un solo uso. Guárdalo de forma segura.")}\n\n${recoveryCode}\n`, "toward-us-recovery-code.txt", "text/plain;charset=utf-8")}><DownloadSimple size={16} />{t("下载到安全位置", "Download and store securely", "Descargar y guardar de forma segura")}</button><button className="privacy-quiet" onClick={() => { setRecoveryCode(""); setShowCode(false); }}>{t("已保存，关闭完整码", "Saved; dismiss the full code", "Guardado; cerrar código completo")}</button></div></div>}
      </section>
      <section className="privacy-section"><h3>{t("数据副本", "Your data copy", "Copia de tus datos")}</h3><p>{t("下载 JSON 格式，方便你保管或转移。旧关系的共同记录也可包含在授权范围内的导出中。", "Download JSON for your own records or transfer. Shared history from previous relationships may also be included within your access rights.", "Descarga JSON para conservar o trasladar tus datos. También puede incluir historial de relaciones anteriores dentro de tus permisos.")}</p><button disabled={busy} onClick={() => prepare({ kind: "export" })}><DownloadSimple size={16} />{t("准备下载数据", "Prepare data download", "Preparar descarga")}</button></section>
      <section className="privacy-section"><h3>{t("我授权的共同摘要", "Shared summaries I authorized", "Resúmenes compartidos que autoricé")}</h3>{data.sharedSummaries.filter((summary) => summary.status === "confirmed").length === 0 ? <p>{t("目前没有你确认分享的共同摘要。", "You have not confirmed any shared summaries yet.", "Todavía no confirmaste resúmenes compartidos.")}</p> : <ul className="privacy-records">{data.sharedSummaries.filter((summary) => summary.status === "confirmed").map((summary) => <li key={summary.id}><p>{summary.text}</p><span className="privacy-meta">v{summary.version} · {!summaryIsCurrent(summary) ? t("关系已结束，共同 AI 不再引用", "Relationship ended; joint AI no longer uses this", "Relación finalizada; la IA compartida ya no lo usa") : summary.withdrawnAt || summary.aiAccessScope === "none" ? t("未来共同 AI 使用已停止", "Future joint AI use stopped", "Uso futuro de IA compartida detenido") : t("共同 AI 可使用这版摘要", "Joint AI may use this version", "La IA compartida puede usar esta versión")}</span>{summaryIsCurrent(summary) && !summary.withdrawnAt && summary.aiAccessScope !== "none" && <button className="privacy-quiet" disabled={busy} onClick={() => prepare({ kind: "withdraw", summary })}>{t("撤回未来 AI 使用", "Withdraw future AI use", "Retirar uso futuro de IA")}</button>}</li>)}</ul>}<p className="privacy-meta">{t("关系记忆有独立的双人授权，可在记忆页面查看或撤回。", "Relationship memories have separate mutual consent, managed on the Memories page.", "Los recuerdos tienen un consentimiento mutuo independiente, gestionado en Recuerdos.")}</p></section>
      <section className="privacy-section privacy-danger"><h3>{t("删除与退出", "Deletion and leaving", "Borrar y salir")}</h3><p>{t(`目前有 ${data.privateCount} 条私人记录。下面每项操作都会先说明范围，再由你确认。`, `There are ${data.privateCount} private records. Each action below explains its scope before you confirm.`, `Hay ${data.privateCount} registros privados. Cada acción explica su alcance antes de que confirmes.`)}</p><div className="privacy-actions"><button disabled={busy} onClick={() => prepare({ kind: "delete-private" })}>{t("删除我的私人内容…", "Delete my private content…", "Borrar mi contenido privado…")}</button>{data.relationships.some((relationship) => ["active", "pending"].includes(relationship.status)) && <button disabled={busy} onClick={() => prepare({ kind: "leave" })}>{t("退出当前关系…", "Leave this relationship…", "Salir de esta relación…")}</button>}<button disabled={busy} onClick={() => prepare({ kind: "account" })}>{t("删除我的账号…", "Delete my account…", "Borrar mi cuenta…")}</button></div></section>
      <details className="privacy-section"><summary>{t("我的同意与操作历史", "My consent and action history", "Mi historial de consentimiento y acciones")}</summary>{data.consentHistory.length === 0 ? <p>{t("暂时没有记录。", "No records yet.", "Todavía no hay registros.")}</p> : <ol className="privacy-history">{data.consentHistory.map((event, index) => <li key={`${event.createdAt}:${index}`}><span>{consentLabel(event.eventType, language)}</span><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString(languageTag(language))}</time>{event.sourceVersion && <span>v{event.sourceVersion}</span>}</li>)}</ol>}<p className="privacy-meta">{t("展示最近50条记录，不包含私人原文。", "Shows the latest 50 records without private originals.", "Muestra los últimos 50 registros sin originales privados.")}</p></details>
    </>}
    {pending && <section className="privacy-confirm" ref={confirmationRef} tabIndex={-1} aria-labelledby="privacy-confirm-title"><h3 id="privacy-confirm-title">{actionTitle(pending)}</h3><p>{actionDescription(pending)}</p>{pending.kind === "withdraw" && <blockquote>{pending.summary.text} · v{pending.summary.version}</blockquote>}<form onSubmit={(event) => { event.preventDefault(); void execute(); }}>
      {pending.kind !== "withdraw" && <label><span>{t("当前密码", "Current password", "Contraseña actual")}</span><KeyboardInput type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={(event) => setPassword(event.target.value)} onBlur={() => keyboard.hide()} /></label>}
      <label className="privacy-checkbox"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>{t("我已读懂上述范围，确认执行这项操作。", "I understand this scope and confirm this action.", "Entiendo este alcance y confirmo esta acción.")}</span></label><div className="privacy-actions"><button type="submit" disabled={busy || !confirmed || (pending.kind !== "withdraw" && !password)}>{busy ? t("正在处理…", "Working…", "Procesando…") : actionTitle(pending)}</button><button type="button" className="privacy-quiet" disabled={busy} onClick={cancel}>{t("取消", "Cancel", "Cancelar")}</button></div></form></section>}
    {notice && <p className="privacy-notice" role="status">{notice}</p>}
  </section>;
}

function consentLabel(eventType: string, language: Language) {
  const labels: Record<string, [string, string, string]> = {
    "privacy.retention_changed": ["更新私人保留期限", "Private retention updated", "Conservación privada actualizada"], "privacy.private_data_deleted": ["删除私人内容", "Private content deleted", "Contenido privado borrado"], "account.recovery_code_rotated": ["生成新恢复码", "New recovery code generated", "Nuevo código generado"], "account.recovered": ["使用恢复码找回账号", "Account recovered with code", "Cuenta recuperada con código"], "relationship.left": ["退出关系", "Left relationship", "Salida de la relación"], "summary.ai_access_withdrawn": ["撤回摘要 AI 使用", "Summary AI use withdrawn", "Uso de IA del resumen retirado"],
    "memory.created": ["保存私人记忆", "Private memory saved", "Recuerdo privado guardado"], "memory.corrected": ["纠正记忆并更新授权", "Memory corrected and consent updated", "Recuerdo corregido y permiso actualizado"], "memory.shared": ["确认分享记忆候选", "Memory candidate shared", "Propuesta de recuerdo compartida"], "memory.ai_approved": ["批准当前版本的记忆 AI 使用", "Current memory version approved for AI", "Versión actual del recuerdo autorizada para IA"], "memory.ai_withdrawn": ["撤回记忆 AI 使用", "Memory AI use withdrawn", "Uso de IA del recuerdo retirado"], "memory.archived": ["归档私人记忆", "Private memory archived", "Recuerdo privado archivado"], "memory.deleted": ["删除私人记忆", "Private memory deleted", "Recuerdo privado borrado"], "checkin.created": ["保存私人轻量记录", "Private check-in saved", "Registro privado guardado"], "checkin.shared": ["确认分享轻量记录", "Check-in share confirmed", "Registro compartido confirmado"], "checkin.deleted": ["删除私人轻量记录", "Private check-in deleted", "Registro privado borrado"],
  };
  return labels[eventType] ? localized(language, ...labels[eventType]) : localized(language, "已记录的内容或授权操作", "Recorded content or consent action", "Acción registrada de contenido o permiso");
}
