import { Bell, CalendarBlank, ClockCounterClockwise, HandHeart, House, ListChecks, PaperPlaneRight, SignOut, Sparkle, UsersThree, LockKey, UserGear } from "@phosphor-icons/react";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { languageTag, languages, localized, type Language } from "../../i18n";
import { DecisionWorkspace } from "../decisions/DecisionWorkspace";
import { ListsPanel } from "../lists/ListsPanel";
import { MilestonesPanel } from "../milestones/MilestonesPanel";
import { NotificationCenter } from "../notifications/NotificationCenter";
import { PrivateAgentWorkspace } from "../private-agent/PrivateAgentWorkspace";
import { relationshipApi } from "../relationship/api";
import type { RelationshipHomePayload } from "../relationship/types";

import { MemoryWorkspace } from "../memories/MemoryWorkspace";
import { CheckinPanel } from "../checkins/CheckinPanel";
import { RemindersPanel, type ReminderTarget } from "../reminders/RemindersPanel";
import "../private-agent/personal.css";

type View = "home" | "talk" | "decide" | "plans" | "moments" | "notifications" | "reminders" | "checkins";
type RoomSummary = { code: string; title: string; updatedAt: string; joined: boolean };

export function RelationshipHome({ user, partnerName, language, rooms, notice, busy, onLanguage, onSetup, onJoin, onHistory, onLogout, onNotice, onPersonal, onPrivacy, onAccessChanged }: { user: { id: string; name: string }; partnerName: string; language: Language; rooms: RoomSummary[]; notice: string; busy: boolean; onLanguage: (language: Language) => void; onSetup: () => void; onJoin: (code: string, join: boolean) => void; onHistory: () => void; onLogout: () => void; onNotice: (value: string) => void; onPersonal: () => void; onPrivacy: () => void; onAccessChanged: () => void }) {
  const [view, setView] = useState<View>(() => { const requested = new URLSearchParams(location.search).get("view"); return ["talk", "decide", "plans", "moments", "notifications", "reminders", "checkins"].includes(requested || "") ? requested as View : "home"; }); const [payload, setPayload] = useState<RelationshipHomePayload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [code, setCode] = useState(""); const [agentPrompt, setAgentPrompt] = useState<{ text: string; intent: "decision" | "plan"; nonce: number } | null>(null);
  const [selection, setSelection] = useState(() => ({ issueId: new URLSearchParams(location.search).get("issue") || undefined, outcomeId: new URLSearchParams(location.search).get("outcome") || undefined }));
  const [reminderTarget, setReminderTarget] = useState<ReminderTarget | undefined>();
  const [reminderTitle, setReminderTitle] = useState("");
  const selectReminder = (target: ReminderTarget, title = "") => { setReminderTarget(target); setReminderTitle(title); setView("reminders"); };
  const openItem = (item: { type: string; id: string }) => {
    if (item.type === "milestone") { history.replaceState(null, "", `/?view=plans&milestone=${encodeURIComponent(item.id)}`); setView("plans"); return; }
    const agreement = item.type === "commitment" ? payload?.graph.agreements.find(a => a.id === payload.graph.commitments.find(c => c.id === item.id)?.agreementId) : payload?.graph.agreements.find(a => a.id === item.id);
    setSelection({ issueId: String(agreement?.sourceIssueId || (item.type === "perspective" ? item.id : "")) || undefined, outcomeId: item.type === "outcome_review" ? item.id : undefined }); setView("decide");
  };
  const refresh = useCallback(async () => { try { const result = await relationshipApi<RelationshipHomePayload>("/api/relationship/home"); if (!result?.graph || !Array.isArray(result.graph.notifications)) throw new Error(localized(language, "共同空间返回了无效数据，请重试。", "The shared space returned invalid data. Please retry.", "El espacio compartido devolvió datos no válidos. Inténtalo de nuevo.")); setPayload(result); setError(""); onNotice(""); } catch (caught) { const message = (caught as Error).message; setError(message); onNotice(message); } finally { setLoading(false); } }, [language, onNotice]);
  useEffect(() => { void refresh(); const events = new EventSource("/api/relationship/events"); events.addEventListener("relationship", () => void refresh()); events.addEventListener("access-ended", () => { events.close(); setPayload(null); onAccessChanged(); }); return () => events.close(); }, [refresh, onAccessChanged]);
  if (loading) return <div className="relationship-loading" role="status"><Sparkle size={25} /><span>{localized(language, "正在整理你们的共同空间…", "Organizing your shared space…", "Organizando su espacio compartido…")}</span></div>;
  if (!payload) return <div className="relationship-loading"><Sparkle size={25} /><p role="alert">{error}</p><button className="secondary-action" onClick={() => { setLoading(true); void refresh(); }}>{localized(language, "重新加载", "Try again", "Reintentar")}</button></div>;
  const unread = payload.graph.notifications.filter((item) => !item.readAt && !item.dismissedAt).length;
  return <div className="paper-screen relationship-shell" data-testid="dashboard-screen"><header className="relationship-header"><button className="relationship-brand" onClick={() => setView("home")}><strong>TOWARD US</strong><span>{language === "zh" ? "彼此" : localized(language, "", "Shared relationship agent", "Agente compartido de relación")}</span></button><nav aria-label={localized(language, "共同空间导航", "Shared-space navigation", "Navegación del espacio compartido")}><NavButton active={view === "home"} onClick={() => setView("home")} icon={<House />} label={localized(language, "首页", "Home", "Inicio")} /><NavButton active={view === "talk"} onClick={() => setView("talk")} icon={<UsersThree />} label={localized(language, "沟通", "Talk", "Hablar")} /><NavButton active={view === "decide"} onClick={() => setView("decide")} icon={<ListChecks />} label={localized(language, "决定", "Decide", "Decidir")} /><NavButton active={view === "plans"} onClick={() => setView("plans")} icon={<CalendarBlank />} label={localized(language, "计划", "Plans", "Planes")} /><NavButton active={view === "moments"} onClick={() => setView("moments")} icon={<HandHeart />} label={localized(language, "回忆", "Moments", "Momentos")} /></nav><div className="relationship-header-actions"><button onClick={onPersonal} aria-label={localized(language, "我的私人空间", "My private space", "Mi espacio privado")}><LockKey size={19} /></button><button onClick={onPrivacy} aria-label={localized(language, "隐私与账号", "Privacy & account", "Privacidad y cuenta")}><UserGear size={19} /></button><button className="notification-button" onClick={() => setView("notifications")} aria-label={localized(language, "通知", "Notifications", "Notificaciones")}><Bell size={19} />{unread > 0 && <span>{unread}</span>}</button><div className="relationship-languages" role="group" aria-label={localized(language, "选择界面语言", "Choose display language", "Elegir idioma")}>{languages.map((item) => <button key={item} className={item === language ? "active" : ""} onClick={() => onLanguage(item)}>{item.toUpperCase()}</button>)}</div><button onClick={onLogout} aria-label={localized(language, "退出登录", "Sign out", "Cerrar sesión")}><SignOut size={19} /></button></div></header>
    <main className="relationship-main">
      {view === "home" && <HomeView language={language} userName={user.name} partnerName={partnerName} payload={payload} onOpen={openItem} onView={setView} onSetup={onSetup} onAgent={(text, intent) => { setAgentPrompt({ text, intent, nonce: Date.now() }); setView(intent === "plan" ? "plans" : "decide"); }} />}
      {view === "talk" && <TalkView language={language} rooms={rooms} code={code} setCode={setCode} busy={busy} notice={notice} onSetup={onSetup} onJoin={onJoin} onHistory={onHistory} />}
      {view === "decide" && <DecisionWorkspace language={language} userId={user.id} graph={payload.graph} members={payload.relationship.members} initialIssueId={selection.issueId} initialOutcomeId={selection.outcomeId} initialPrompt={agentPrompt?.intent === "decision" ? agentPrompt : null} onChanged={refresh} />}
      {view === "decide" && <div className="lifecycle-tools"><button onClick={() => selectReminder(selection.outcomeId ? { kind: "outcome", id: selection.outcomeId } : selection.issueId ? { kind: "issue", id: selection.issueId } : { kind: "reminders" })}>{localized(language, "设置我的跟进提醒", "Set my follow-up reminder", "Configurar mi recordatorio de seguimiento")}</button></div>}
      {view === "plans" && <div className="feature-stack"><PrivateAgentWorkspace language={language} userId={user.id} intentType="plan" threads={payload.graph.privateAgentThreads} onShared={(id) => { history.replaceState(null, "", `/?view=plans&milestone=${encodeURIComponent(id)}`); }} initialPrompt={agentPrompt?.intent === "plan" ? agentPrompt : null} onChanged={refresh} /><div className="lifecycle-tools"><button onClick={() => selectReminder({ kind: "plans" })}>{localized(language, "管理我的提醒", "Manage my reminders", "Gestionar mis recordatorios")}</button></div><details className="manual-tools plan-manual" open={Boolean(new URLSearchParams(location.search).get("milestone"))}><summary>{localized(language, "手动编辑日期与清单（备用）", "Edit dates and lists manually (optional)", "Editar fechas y listas manualmente (opcional)")}</summary><div className="feature-stack"><MilestonesPanel language={language} milestones={payload.graph.milestones} reminders={payload.graph.reminders} onRemind={(id, title) => selectReminder({ kind: "milestone", id }, title)} onChanged={refresh} /><ListsPanel language={language} lists={payload.graph.lists} items={payload.graph.listItems} onChanged={refresh} /></div></details></div>}
      {(view === "moments" || view === "checkins") && <div className="feature-stack"><CheckinPanel language={language} userId={user.id} relationshipId={payload.relationship.id} onChanged={refresh} /><div className="lifecycle-tools"><button onClick={() => selectReminder({ kind: "checkins" }, localized(language, "留一分钟给自己", "A minute for yourself", "Un minuto para ti"))}>{localized(language, "提醒我记录日常", "Remind me to check in", "Recordarme un momento diario")}</button></div><MemoryWorkspace language={language} userId={user.id} relationshipId={payload.relationship.id} onChanged={refresh} /></div>}
      {view === "reminders" && <RemindersPanel key={`${reminderTarget?.kind}:${reminderTarget?.id}`} language={language} initialTarget={reminderTarget} initialTitle={reminderTitle} onChanged={refresh} />}
      {view === "notifications" && <NotificationCenter language={language} notifications={payload.graph.notifications} onChanged={refresh} />}
      {view === "notifications" && <div className="lifecycle-tools"><button onClick={() => selectReminder({ kind: "reminders" })}>{localized(language, "提醒与设备设置", "Reminders & devices", "Recordatorios y dispositivos")}</button></div>}
    </main>
  </div>;
}

function HomeView({ language, userName, partnerName, payload, onView, onSetup, onAgent, onOpen }: { language: Language; userName: string; partnerName: string; payload: RelationshipHomePayload; onView: (view: View) => void; onSetup: () => void; onAgent: (text: string, intent: "decision" | "plan") => void; onOpen: (item: { type: string; id: string }) => void }) {
  const [prompt, setPrompt] = useState(""); const begin = () => { const text = prompt.trim(); if (!text) return; const intent = /(计划|安排|提醒|日期|旅行|约会|生日|周年|plan|schedule|remind|trip|date|viaje|fecha)/i.test(text) ? "plan" : "decision"; onAgent(text, intent); setPrompt(""); };
  return <div className="relationship-home"><header className="relationship-hero"><div className="relationship-color-field red" aria-hidden="true" /><div className="relationship-color-field blue" aria-hidden="true" /><p>{localized(language, "属于两个人，也尊重每个人的内心空间", "For both of you, with room to think alone", "Para ambos, con espacio para pensar a solas")}</p><h1>{userName}<i>＋</i>{partnerName}</h1><span>{localized(language, "先和 AI 说出你的真实想法，它会替你整理、记住并推进。", "Tell AI what’s really on your mind. It organizes, remembers, and moves things forward.", "Cuéntale a la IA lo que realmente piensas. Lo organiza, lo recuerda y lo hace avanzar.")}</span><small>{localized(language, "私人想法默认只属于你；共同事项只有在你明确分享后才会出现。", "Private thoughts stay yours. Shared matters appear only after you explicitly share them.", "Tus pensamientos privados siguen siendo tuyos. Los asuntos compartidos aparecen solo cuando los compartes expresamente.")}</small><div className="home-agent-composer"><Sparkle size={22} weight="fill" /><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder={localized(language, "告诉我你正在想什么、想做什么，或需要我记住什么…", "Tell me what you’re thinking, planning, or want me to remember…", "Cuéntame qué piensas, qué planeas o qué quieres que recuerde…")} rows={2} maxLength={2000} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); begin(); } }} /><button type="button" onClick={begin} disabled={!prompt.trim()} aria-label={localized(language, "开始和 Agent 对话", "Start talking with Agent", "Empezar a hablar con el agente")}><PaperPlaneRight size={20} weight="fill" /></button></div></header>
    <div className="relationship-actions"><button onClick={onSetup}><UsersThree size={23} /><strong>{localized(language, "一起聊清楚", "Talk it through", "Hablarlo juntos")}</strong><span>{localized(language, "调解与复盘", "Mediation & review", "Mediación y revisión")}</span></button><button onClick={() => onView("decide")}><ListChecks size={23} /><strong>{localized(language, "一起做决定", "Make a decision", "Tomar una decisión")}</strong><span>{localized(language, "双方观点与双批准", "Two perspectives, two approvals", "Dos perspectivas, dos aprobaciones")}</span></button><button onClick={() => onView("plans")}><CalendarBlank size={23} /><strong>{localized(language, "一起计划", "Plan something", "Planear algo")}</strong><span>{localized(language, "日期、提醒与愿望", "Dates, reminders & wishes", "Fechas, recordatorios y deseos")}</span></button><button onClick={() => onView("moments")}><HandHeart size={23} /><strong>{localized(language, "记住这一刻", "Save a moment", "Guardar un momento")}</strong><span>{localized(language, "日常记录与经过确认的记忆", "Daily notes & confirmed memories", "Notas diarias y recuerdos confirmados")}</span></button></div>
    <div className="home-columns"><HomeSection title={localized(language, "等待双方", "Needs both of you", "Necesita a ambos")} empty={localized(language, "目前没有等待你处理的共同事项。", "Nothing is waiting on you right now.", "No hay asuntos compartidos pendientes.")} items={payload.home.pending.map((item) => ({ id: item.id, onClick: () => onOpen(item), title: item.type === "outcome_review" ? localized(language, "结果复盘已到期", "Outcome review is due", "La revisión del resultado está pendiente") : item.title, meta: relationshipLabel(language, item.type) }))} /><HomeSection title={localized(language, "即将到来", "Coming up", "Próximamente")} empty={localized(language, "添加一个共同日期后会显示在这里。", "Add a shared date and it will appear here.", "Añade una fecha compartida y aparecerá aquí.")} items={payload.home.upcoming.map((item) => ({ id: item.id, onClick: () => onOpen(item), title: item.title, meta: new Date(item.at).toLocaleDateString(languageTag(language)) }))} /><HomeSection title={localized(language, "正在进行", "Plans in motion", "Planes en marcha")} empty={localized(language, "双方批准的决定和承诺会显示在这里。", "Approved agreements and commitments will appear here.", "Los acuerdos y compromisos aprobados aparecerán aquí.")} items={payload.home.plans.map((item) => ({ id: item.id, onClick: () => onOpen(item), title: item.title, meta: relationshipLabel(language, item.status) }))} /></div>
  </div>;
}

function TalkView({ language, rooms, code, setCode, busy, notice, onSetup, onJoin, onHistory }: { language: Language; rooms: RoomSummary[]; code: string; setCode: (value: string) => void; busy: boolean; notice: string; onSetup: () => void; onJoin: (code: string, join: boolean) => void; onHistory: () => void }) {
  return <section className="relationship-feature talk-view"><header><div><UsersThree size={24} /><h2>{localized(language, "沟通与调解", "Talk & mediate", "Hablar y mediar")}</h2></div><p>{localized(language, "原有调解、实时语音、私人反馈与共同复盘完整保留。", "Mediation, live voice, private feedback, and shared reviews remain intact.", "Se conservan la mediación, la voz en vivo, los comentarios privados y las revisiones compartidas.")}</p></header><button className="relationship-primary" onClick={onSetup}>{localized(language, "开始一次调解", "Start a mediation", "Iniciar una mediación")}</button><div className="join-relationship-room"><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))} placeholder={localized(language, "六位房间码", "Six-character room code", "Código de seis caracteres")} maxLength={6} /><button data-testid="join-active-room" onClick={() => onJoin(code, true)} disabled={busy || code.length !== 6}><PaperPlaneRight size={19} /></button></div>{notice && <p role="alert" className="relationship-notice">{notice}</p>}<div className="relationship-rows">{rooms.map((room) => <article key={room.code}><div><strong>{room.title}</strong><span>{room.code}</span></div><button onClick={() => onJoin(room.code, !room.joined)}>{localized(language, "打开", "Open", "Abrir")}</button></article>)}</div><button className="text-action history-action" onClick={onHistory}><ClockCounterClockwise size={18} />{localized(language, "查看我们的复盘", "Open our reviews", "Abrir nuestras revisiones")}</button></section>;
}

function HomeSection({ title, empty, items }: { title: string; empty: string; items: Array<{ id: string; title: string; meta: string; onClick: () => void }> }) { return <section className="home-section"><h2>{title}</h2>{items.length ? items.map((item) => <article key={`${item.id}:${item.meta}`}><button onClick={item.onClick}><strong>{item.title}</strong><span>{item.meta}</span></button></article>) : <p>{empty}</p>}</section>; }
function NavButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: ReactNode; label: string }) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{label}</span></button>; }
function relationshipLabel(language: Language, value: string) { const labels: Record<string, [string, string, string]> = { perspective: ["提交我的观点", "My perspective", "Mi perspectiva"], approval: ["等待我的批准", "My approval", "Mi aprobación"], outcome_review: ["结果复盘", "Outcome review", "Revisión del resultado"], active: ["进行中", "Active", "Activo"], renegotiation_requested: ["请求重新协商", "Renegotiation requested", "Renegociación solicitada"] }; const label = labels[value]; return label ? localized(language, ...label) : value; }
