import { Bell, CalendarBlank, ClockCounterClockwise, HandHeart, House, ListChecks, PaperPlaneRight, SignOut, Sparkle, UsersThree } from "@phosphor-icons/react";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { languageTag, languages, localized, type Language } from "../../i18n";
import { DecisionWorkspace } from "../decisions/DecisionWorkspace";
import { ListsPanel } from "../lists/ListsPanel";
import { MilestonesPanel } from "../milestones/MilestonesPanel";
import { NotificationCenter } from "../notifications/NotificationCenter";
import { relationshipApi } from "../relationship/api";
import type { RelationshipHomePayload } from "../relationship/types";

type View = "home" | "talk" | "decide" | "plans" | "moments" | "notifications";
type RoomSummary = { code: string; title: string; updatedAt: string; joined: boolean };

export function RelationshipHome({ user, partnerName, language, rooms, notice, busy, onLanguage, onSetup, onJoin, onHistory, onLogout, onNotice }: { user: { id: string; name: string }; partnerName: string; language: Language; rooms: RoomSummary[]; notice: string; busy: boolean; onLanguage: (language: Language) => void; onSetup: () => void; onJoin: (code: string, join: boolean) => void; onHistory: () => void; onLogout: () => void; onNotice: (value: string) => void }) {
  const [view, setView] = useState<View>("home"); const [payload, setPayload] = useState<RelationshipHomePayload | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [code, setCode] = useState("");
  const refresh = useCallback(async () => { try { const result = await relationshipApi<RelationshipHomePayload>("/api/relationship/home"); if (!result?.graph || !Array.isArray(result.graph.notifications)) throw new Error(localized(language, "共同空间返回了无效数据，请重试。", "The shared space returned invalid data. Please retry.", "El espacio compartido devolvió datos no válidos. Inténtalo de nuevo.")); setPayload(result); setError(""); onNotice(""); } catch (caught) { const message = (caught as Error).message; setError(message); onNotice(message); } finally { setLoading(false); } }, [language, onNotice]);
  useEffect(() => { void refresh(); const events = new EventSource("/api/relationship/events"); events.addEventListener("relationship", () => void refresh()); return () => events.close(); }, [refresh]);
  if (loading) return <div className="relationship-loading" role="status"><Sparkle size={25} /><span>{localized(language, "正在整理你们的共同空间…", "Organizing your shared space…", "Organizando su espacio compartido…")}</span></div>;
  if (!payload) return <div className="relationship-loading"><Sparkle size={25} /><p role="alert">{error}</p><button className="secondary-action" onClick={() => { setLoading(true); void refresh(); }}>{localized(language, "重新加载", "Try again", "Reintentar")}</button></div>;
  const unread = payload.graph.notifications.filter((item) => !item.readAt && !item.dismissedAt).length;
  return <div className="paper-screen relationship-shell" data-testid="dashboard-screen"><header className="relationship-header"><button className="relationship-brand" onClick={() => setView("home")}><strong>TOWARD US</strong><span>{language === "zh" ? "彼此" : localized(language, "", "Shared relationship agent", "Agente compartido de relación")}</span></button><nav aria-label={localized(language, "共同空间导航", "Shared-space navigation", "Navegación del espacio compartido")}><NavButton active={view === "home"} onClick={() => setView("home")} icon={<House />} label={localized(language, "首页", "Home", "Inicio")} /><NavButton active={view === "talk"} onClick={() => setView("talk")} icon={<UsersThree />} label={localized(language, "沟通", "Talk", "Hablar")} /><NavButton active={view === "decide"} onClick={() => setView("decide")} icon={<ListChecks />} label={localized(language, "决定", "Decide", "Decidir")} /><NavButton active={view === "plans"} onClick={() => setView("plans")} icon={<CalendarBlank />} label={localized(language, "计划", "Plans", "Planes")} /><NavButton active={view === "moments"} onClick={() => setView("moments")} icon={<HandHeart />} label={localized(language, "回忆", "Moments", "Momentos")} /></nav><div className="relationship-header-actions"><button className="notification-button" onClick={() => setView("notifications")} aria-label={localized(language, "通知", "Notifications", "Notificaciones")}><Bell size={19} />{unread > 0 && <span>{unread}</span>}</button><div className="relationship-languages" role="group" aria-label={localized(language, "选择界面语言", "Choose display language", "Elegir idioma")}>{languages.map((item) => <button key={item} className={item === language ? "active" : ""} onClick={() => onLanguage(item)}>{item.toUpperCase()}</button>)}</div><button onClick={onLogout} aria-label={localized(language, "退出登录", "Sign out", "Cerrar sesión")}><SignOut size={19} /></button></div></header>
    <main className="relationship-main">
      {view === "home" && <HomeView language={language} userName={user.name} partnerName={partnerName} payload={payload} onView={setView} onSetup={onSetup} />}
      {view === "talk" && <TalkView language={language} rooms={rooms} code={code} setCode={setCode} busy={busy} notice={notice} onSetup={onSetup} onJoin={onJoin} onHistory={onHistory} />}
      {view === "decide" && <DecisionWorkspace language={language} userId={user.id} graph={payload.graph} onChanged={refresh} />}
      {view === "plans" && <div className="feature-stack"><MilestonesPanel language={language} milestones={payload.graph.milestones} reminders={payload.graph.reminders} onChanged={refresh} /><ListsPanel language={language} lists={payload.graph.lists} items={payload.graph.listItems} onChanged={refresh} /></div>}
      {view === "moments" && <section className="relationship-feature moment-empty"><HandHeart size={40} /><h2>{localized(language, "我们的一段回忆", "A moment from us", "Un momento nuestro")}</h2><p>{localized(language, "共同回忆时间线属于 P1。本轮没有制造假数据，也不会把单方记忆自动写成双方事实。", "The shared memory timeline is P1. No fake moments are shown, and one person's memory never becomes a joint fact automatically.", "La cronología de recuerdos es P1. No mostramos momentos ficticios y el recuerdo de una persona nunca se convierte automáticamente en un hecho compartido.")}</p></section>}
      {view === "notifications" && <NotificationCenter language={language} notifications={payload.graph.notifications} onChanged={refresh} />}
    </main>
  </div>;
}

function HomeView({ language, userName, partnerName, payload, onView, onSetup }: { language: Language; userName: string; partnerName: string; payload: RelationshipHomePayload; onView: (view: View) => void; onSetup: () => void }) {
  return <div className="relationship-home"><header className="relationship-hero"><p>{localized(language, "属于两个人的共同关系 Agent", "A shared relationship agent for two people", "Un agente compartido de relación para dos personas")}</p><h1>{userName}<i>＋</i>{partnerName}</h1><span>{localized(language, "一起沟通、决定、计划、记住，并把说过的话真正做到。", "Talk, decide, plan, remember, and follow through together.", "Hablar, decidir, planear, recordar y cumplir juntos.")}</span><small>{localized(language, "它属于你们两个人，但任何一方都不能单独控制它。", "It belongs to both of you, but neither person controls it alone.", "Les pertenece a ambos, pero ninguno lo controla por sí solo.")}</small></header>
    <div className="relationship-actions"><button onClick={onSetup}><UsersThree size={23} /><strong>{localized(language, "一起聊清楚", "Talk it through", "Hablarlo juntos")}</strong><span>{localized(language, "调解与复盘", "Mediation & review", "Mediación y revisión")}</span></button><button onClick={() => onView("decide")}><ListChecks size={23} /><strong>{localized(language, "一起做决定", "Make a decision", "Tomar una decisión")}</strong><span>{localized(language, "双方观点与双批准", "Two perspectives, two approvals", "Dos perspectivas, dos aprobaciones")}</span></button><button onClick={() => onView("plans")}><CalendarBlank size={23} /><strong>{localized(language, "一起计划", "Plan something", "Planear algo")}</strong><span>{localized(language, "日期、提醒与愿望", "Dates, reminders & wishes", "Fechas, recordatorios y deseos")}</span></button><button onClick={() => onView("moments")}><HandHeart size={23} /><strong>{localized(language, "记住这一刻", "Save a moment", "Guardar un momento")}</strong><span>P1</span></button></div>
    <div className="home-columns"><HomeSection title={localized(language, "等待双方", "Needs both of you", "Necesita a ambos")} empty={localized(language, "目前没有等待你处理的共同事项。", "Nothing is waiting on you right now.", "No hay asuntos compartidos pendientes.")} items={payload.home.pending.map((item) => ({ id: item.id, title: item.type === "outcome_review" ? localized(language, "结果复盘已到期", "Outcome review is due", "La revisión del resultado está pendiente") : item.title, meta: relationshipLabel(language, item.type) }))} /><HomeSection title={localized(language, "即将到来", "Coming up", "Próximamente")} empty={localized(language, "添加一个共同日期后会显示在这里。", "Add a shared date and it will appear here.", "Añade una fecha compartida y aparecerá aquí.")} items={payload.home.upcoming.map((item) => ({ id: item.id, title: item.title, meta: new Date(item.at).toLocaleDateString(languageTag(language)) }))} /><HomeSection title={localized(language, "正在进行", "Plans in motion", "Planes en marcha")} empty={localized(language, "双方批准的决定和承诺会显示在这里。", "Approved agreements and commitments will appear here.", "Los acuerdos y compromisos aprobados aparecerán aquí.")} items={payload.home.plans.map((item) => ({ id: item.id, title: item.title, meta: relationshipLabel(language, item.status) }))} /></div>
  </div>;
}

function TalkView({ language, rooms, code, setCode, busy, notice, onSetup, onJoin, onHistory }: { language: Language; rooms: RoomSummary[]; code: string; setCode: (value: string) => void; busy: boolean; notice: string; onSetup: () => void; onJoin: (code: string, join: boolean) => void; onHistory: () => void }) {
  return <section className="relationship-feature talk-view"><header><div><UsersThree size={24} /><h2>{localized(language, "沟通与调解", "Talk & mediate", "Hablar y mediar")}</h2></div><p>{localized(language, "原有调解、实时语音、私人反馈与共同复盘完整保留。", "Mediation, live voice, private feedback, and shared reviews remain intact.", "Se conservan la mediación, la voz en vivo, los comentarios privados y las revisiones compartidas.")}</p></header><button className="relationship-primary" onClick={onSetup}>{localized(language, "开始一次调解", "Start a mediation", "Iniciar una mediación")}</button><div className="join-relationship-room"><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6))} placeholder={localized(language, "六位房间码", "Six-character room code", "Código de seis caracteres")} maxLength={6} /><button data-testid="join-active-room" onClick={() => onJoin(code, true)} disabled={busy || code.length !== 6}><PaperPlaneRight size={19} /></button></div>{notice && <p role="alert" className="relationship-notice">{notice}</p>}<div className="relationship-rows">{rooms.map((room) => <article key={room.code}><div><strong>{room.title}</strong><span>{room.code}</span></div><button onClick={() => onJoin(room.code, !room.joined)}>{localized(language, "打开", "Open", "Abrir")}</button></article>)}</div><button className="text-action history-action" onClick={onHistory}><ClockCounterClockwise size={18} />{localized(language, "查看我们的复盘", "Open our reviews", "Abrir nuestras revisiones")}</button></section>;
}

function HomeSection({ title, empty, items }: { title: string; empty: string; items: Array<{ id: string; title: string; meta: string }> }) { return <section className="home-section"><h2>{title}</h2>{items.length ? items.map((item) => <article key={`${item.id}:${item.meta}`}><strong>{item.title}</strong><span>{item.meta}</span></article>) : <p>{empty}</p>}</section>; }
function NavButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: ReactNode; label: string }) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{label}</span></button>; }
function relationshipLabel(language: Language, value: string) { const labels: Record<string, [string, string, string]> = { perspective: ["提交我的观点", "My perspective", "Mi perspectiva"], approval: ["等待我的批准", "My approval", "Mi aprobación"], outcome_review: ["结果复盘", "Outcome review", "Revisión del resultado"], active: ["进行中", "Active", "Activo"], renegotiation_requested: ["请求重新协商", "Renegotiation requested", "Renegociación solicitada"] }; const label = labels[value]; return label ? localized(language, ...label) : value; }
